import type { ScenarioBoardDefinition } from '../../../engine/index.ts';
import { IRAN_SCENARIO_MARKERS } from './generatedScenarioAnchors.ts';

export const womanLifeFreedomBoard: ScenarioBoardDefinition = {
  assetPath: '/assets/scenarios/woman_life_freedom/iran-location-map.svg',
  sourceViewBox: '0 0 1000 800',
  viewport: {
    canvasWidth: '100%',
    canvasHeight: '100%',
    canvasLeft: '0%',
    canvasTop: '0%',
  },
  svgIdConvention: 'GeoJSON-derived Iranian scenario regions and city anchors.',
  regions: {
    Tehran: {
      regionId: 'Tehran',
      label: 'Tehran',
      marker: { ...IRAN_SCENARIO_MARKERS.Tehran },
      tokenAnchor: { ...IRAN_SCENARIO_MARKERS.Tehran },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 70,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '-18px', y: '-22px' },
      tooltipOffset: { x: '-94px', y: '-190px' },
      territoryTilt: '0deg',
      accent: '#92644f',
      searchTerms: ['tehran'],
      focusDomains: ['WarMachine', 'SilencedTruth', 'PatriarchalGrip'],
      anchorCoverage: ['tehran-shape'],
      interactionCoverage: ['tehran-shape'],
      svgCoverage: ['tehran-region'],
      note: 'Capital convergence of campuses, prisons, and public witness.',
    },
    Kurdistan: {
      regionId: 'Kurdistan',
      label: 'Kurdistan',
      marker: { ...IRAN_SCENARIO_MARKERS.Kurdistan },
      tokenAnchor: { ...IRAN_SCENARIO_MARKERS.Kurdistan },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 70,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '-42px', y: '-20px' },
      tooltipOffset: { x: '-124px', y: '-188px' },
      territoryTilt: '-2deg',
      accent: '#b2774d',
      searchTerms: ['kurdistan'],
      focusDomains: ['WarMachine', 'StolenVoice', 'PatriarchalGrip'],
      anchorCoverage: ['kurdistan-shape'],
      interactionCoverage: ['kurdistan-shape'],
      svgCoverage: ['kurdistan-region'],
      note: 'Movement vanguard rooted in Kurdish struggle and state backlash.',
    },
    Isfahan: {
      regionId: 'Isfahan',
      label: 'Isfahan',
      marker: { ...IRAN_SCENARIO_MARKERS.Isfahan },
      tokenAnchor: { ...IRAN_SCENARIO_MARKERS.Isfahan },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 68,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '-18px', y: '-20px' },
      tooltipOffset: { x: '-94px', y: '-188px' },
      territoryTilt: '-1deg',
      accent: '#8a613f',
      searchTerms: ['isfahan'],
      focusDomains: ['PatriarchalGrip', 'DyingPlanet', 'EmptyStomach'],
      anchorCoverage: ['isfahan-shape'],
      interactionCoverage: ['isfahan-shape'],
      svgCoverage: ['isfahan-region'],
      note: 'Water crisis, schoolgirl resistance, and urban continuity.',
    },
    Mashhad: {
      regionId: 'Mashhad',
      label: 'Mashhad',
      marker: { ...IRAN_SCENARIO_MARKERS.Mashhad },
      tokenAnchor: { ...IRAN_SCENARIO_MARKERS.Mashhad },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 68,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '20px', y: '-20px' },
      tooltipOffset: { x: '-84px', y: '-188px' },
      territoryTilt: '2deg',
      accent: '#a36d52',
      searchTerms: ['mashhad'],
      focusDomains: ['PatriarchalGrip', 'GildedCage', 'SilencedTruth'],
      anchorCoverage: ['mashhad-shape'],
      interactionCoverage: ['mashhad-shape'],
      svgCoverage: ['mashhad-region'],
      note: 'Shrine-city rupture where dissent breaks expected containment.',
    },
    Khuzestan: {
      regionId: 'Khuzestan',
      label: 'Khuzestan',
      marker: { ...IRAN_SCENARIO_MARKERS.Khuzestan },
      tokenAnchor: { ...IRAN_SCENARIO_MARKERS.Khuzestan },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 70,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '-26px', y: '-18px' },
      tooltipOffset: { x: '-108px', y: '-188px' },
      territoryTilt: '-3deg',
      accent: '#7c4f3d',
      searchTerms: ['khuzestan'],
      focusDomains: ['DyingPlanet', 'FossilGrip', 'WarMachine'],
      anchorCoverage: ['khuzestan-shape'],
      interactionCoverage: ['khuzestan-shape'],
      svgCoverage: ['khuzestan-region'],
      note: 'Oil wealth, ecological crisis, and ethnic marginalization converge here.',
    },
    Balochistan: {
      regionId: 'Balochistan',
      label: 'Balochistan',
      marker: { ...IRAN_SCENARIO_MARKERS.Balochistan },
      tokenAnchor: { ...IRAN_SCENARIO_MARKERS.Balochistan },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 70,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '18px', y: '-20px' },
      tooltipOffset: { x: '-88px', y: '-188px' },
      territoryTilt: '3deg',
      accent: '#6f4738',
      searchTerms: ['balochistan'],
      focusDomains: ['WarMachine', 'StolenVoice', 'EmptyStomach'],
      anchorCoverage: ['balochistan-shape'],
      interactionCoverage: ['balochistan-shape'],
      svgCoverage: ['balochistan-region'],
      note: 'Peripheral frontier marked by massacre, Friday protest, and endurance.',
    },
  },
};
