import type { ScenarioBoardDefinition } from '../../../engine/index.ts';
import { baseWorldBoard } from '../../stones_cry_out/boards/baseWorldBoard.ts';

export const corridorsBurnBoard: ScenarioBoardDefinition = {
  assetPath: baseWorldBoard.assetPath,
  sourceViewBox: baseWorldBoard.sourceViewBox,
  viewport: baseWorldBoard.viewport,
  svgIdConvention: baseWorldBoard.svgIdConvention,
  regions: {
    GazaWestBank: {
      regionId: 'GazaWestBank',
      label: 'Gaza–West Bank',
      marker: { x: '57.11%', y: '47.99%' },
      tokenAnchor: { x: '57.11%', y: '47.99%' },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 66,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '24px', y: '-18px' },
      tooltipOffset: { x: '-52px', y: '-224px' },
      territoryTilt: '2deg',
      accent: '#9b4a3f',
      searchTerms: ['gaza', 'west bank', 'rafah', 'jenin', 'hebron', 'palestine'],
      focusDomains: ['WarMachine', 'GildedCage', 'SilencedTruth', 'EmptyStomach'],
      anchorCoverage: ['il', 'jo', 'eg'],
      interactionCoverage: ['il', 'jo'],
      svgCoverage: ['il', 'jo', 'eg', 'lb', 'sy'],
      note: 'The theatre centers Gaza and the West Bank while using Jordan and northeast Egypt as the corridor geometry around a missing Palestine path.',
    },
    LebanonNorthernFront: {
      regionId: 'LebanonNorthernFront',
      label: 'Lebanon–Northern Front',
      marker: { x: '58.98%', y: '43.44%' },
      tokenAnchor: { x: '58.98%', y: '43.44%' },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 64,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '24px', y: '-18px' },
      tooltipOffset: { x: '-28px', y: '-220px' },
      territoryTilt: '3deg',
      accent: '#7f5a49',
      searchTerms: ['lebanon', 'beirut', 'south lebanon', 'galilee', 'northern front'],
      focusDomains: ['WarMachine', 'SilencedTruth', 'RevolutionaryWave'],
      anchorCoverage: ['lb', 'sy', 'il'],
      interactionCoverage: ['lb', 'sy', 'il'],
      svgCoverage: ['lb', 'sy', 'il', 'jo', 'tr', 'cy'],
      note: 'Lebanon and the northern Israeli frontier are bounded through Lebanon-Syria-Israel geometry with Cyprus and Turkey as nearby reference space.',
    },
    GulfHormuzCorridor: {
      regionId: 'GulfHormuzCorridor',
      label: 'Gulf–Hormuz Corridor',
      marker: { x: '62.62%', y: '47.10%' },
      tokenAnchor: { x: '62.62%', y: '47.10%' },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 70,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '28px', y: '-18px' },
      tooltipOffset: { x: '-8px', y: '-224px' },
      territoryTilt: '5deg',
      accent: '#9a6f44',
      searchTerms: ['hormuz', 'gulf', 'iran', 'iraq', 'qatar', 'uae', 'kuwait', 'saudi', 'oman'],
      focusDomains: ['WarMachine', 'FossilGrip', 'EmptyStomach'],
      anchorCoverage: ['ir', 'iq', 'kw', 'qa', 'ae', 'om', 'sa'],
      interactionCoverage: ['ir', 'iq', 'kw', 'qa', 'ae', 'om'],
      svgCoverage: ['ir', 'iq', 'kw', 'qa', 'ae', 'om', 'sa'],
      note: 'Iran, Iraq, Kuwait, Qatar, UAE, Oman, and eastern Saudi Arabia form the oil-basing corridor under Hormuz pressure. Bahrain is represented through the subsystem rather than map geometry.',
    },
    RedSeaSuezCorridor: {
      regionId: 'RedSeaSuezCorridor',
      label: 'Red Sea–Suez Corridor',
      marker: { x: '60.17%', y: '49.72%' },
      tokenAnchor: { x: '60.17%', y: '49.72%' },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 72,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '-18px', y: '-18px' },
      tooltipOffset: { x: '-12px', y: '-222px' },
      territoryTilt: '-2deg',
      accent: '#b07f4d',
      searchTerms: ['red sea', 'suez', 'rafah', 'egypt', 'saudi', 'yemen', 'shipping'],
      focusDomains: ['EmptyStomach', 'FossilGrip', 'SilencedTruth'],
      anchorCoverage: ['eg', 'sa', 'ye', 'jo'],
      interactionCoverage: ['eg', 'sa', 'ye', 'jo'],
      svgCoverage: ['eg', 'sa', 'ye', 'jo', 'om'],
      note: 'The corridor runs from Suez and Sinai down the Saudi-Yemeni shoreline, with Jordan anchoring the northern transit hinge.',
    },
    CaribbeanSiege: {
      regionId: 'CaribbeanSiege',
      label: 'Caribbean Siege',
      marker: { x: '26.95%', y: '57.74%' },
      tokenAnchor: { x: '26.95%', y: '57.74%' },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 78,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '16px', y: '-18px' },
      tooltipOffset: { x: '18px', y: '-214px' },
      territoryTilt: '-6deg',
      accent: '#6d6d95',
      searchTerms: ['caribbean', 'cuba', 'venezuela', 'blockade', 'sanctions', 'havana', 'caracas'],
      focusDomains: ['GildedCage', 'EmptyStomach', 'StolenVoice'],
      anchorCoverage: ['cu', 've', 'tt', 'bs'],
      interactionCoverage: ['cu', 've'],
      svgCoverage: ['cu', 've', 'tt', 'bs', 'co'],
      note: 'Cuba and Venezuela anchor the hemisphere siege theatre, with Trinidad and the Bahamas used to broaden the maritime envelope.',
    },
    BlackSeaEasternFurnace: {
      regionId: 'BlackSeaEasternFurnace',
      label: 'Black Sea–Eastern Furnace',
      marker: { x: '73.37%', y: '19.46%' },
      tokenAnchor: { x: '73.37%', y: '19.46%' },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 74,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '18px', y: '-18px' },
      tooltipOffset: { x: '-56px', y: '-224px' },
      territoryTilt: '4deg',
      accent: '#7e6661',
      searchTerms: ['black sea', 'ukraine', 'russia', 'grain corridor', 'crimea', 'odessa', 'donbas'],
      focusDomains: ['WarMachine', 'SilencedTruth', 'EmptyStomach'],
      anchorCoverage: ['ua', 'ru', 'tr', 'ro', 'bg', 'md', 'ge'],
      interactionCoverage: ['ua', 'ru', 'tr', 'ro', 'bg', 'md', 'ge'],
      svgCoverage: ['ua', 'ru', 'tr', 'ro', 'bg', 'md', 'ge'],
      note: 'Ukraine, Russia, Turkey, Romania, Bulgaria, Moldova, and Georgia define the Black Sea war-and-grain furnace in the broader corridor conflict.',
    },
  },
};

export default corridorsBurnBoard;
