// Generated by scripts/generate-scenario-maps.mjs from checked-in GeoJSON.
// The board manifests spread these values so authored offsets remain readable
// while the actual anchor positions stay tied to the underlying geography.

export const EGYPT_SCENARIO_MARKERS = {
  Cairo: { x: '52.92%', y: '20.42%' },
  Alexandria: { x: '43.93%', y: '9.18%' },
  NileDelta: { x: '53.74%', y: '10.73%' },
  UpperEgypt: { x: '52.58%', y: '47.73%' },
  Suez: { x: '61.64%', y: '21.10%' },
  Sinai: { x: '70.09%', y: '9.92%' },
} as const;

export const IRAN_SCENARIO_MARKERS = {
  Tehran: { x: '40.48%', y: '31.38%' },
  Kurdistan: { x: '22.24%', y: '33.78%' },
  Isfahan: { x: '41.62%', y: '50.32%' },
  Mashhad: { x: '74.60%', y: '27.48%' },
  Khuzestan: { x: '29.22%', y: '58.58%' },
  Balochistan: { x: '79.77%', y: '69.59%' },
} as const;
