// Generated by scripts/generate-scenario-maps.mjs from checked-in GeoJSON.
// The board manifests spread these values so authored offsets remain readable
// while token anchors stay tied to region geometry.

export const EGYPT_SCENARIO_MARKERS = {
  Cairo: { x: '52.92%', y: '20.42%' },
  Alexandria: { x: '43.93%', y: '9.18%' },
  NileDelta: { x: '53.74%', y: '10.73%' },
  UpperEgypt: { x: '52.58%', y: '47.73%' },
  Suez: { x: '61.64%', y: '21.10%' },
  Sinai: { x: '70.09%', y: '9.92%' },
} as const;

export const IRAN_SCENARIO_MARKERS = {
  Tehran: { x: '40.48%', y: '31.38%' },
  Kurdistan: { x: '22.24%', y: '33.78%' },
  Isfahan: { x: '41.62%', y: '50.32%' },
  Mashhad: { x: '74.60%', y: '27.48%' },
  Khuzestan: { x: '29.22%', y: '58.58%' },
  Balochistan: { x: '79.77%', y: '69.59%' },
} as const;

export const ALGERIA_SCENARIO_MARKERS = {
  Algiers: { x: '54.90%', y: '6.37%' },
  KabylieMountains: { x: '58.38%', y: '6.60%' },
  Oran: { x: '41.95%', y: '12.14%' },
  SaharaSouth: { x: '63.58%', y: '77.49%' },
  TunisianBorder: { x: '72.74%', y: '13.72%' },
  FrenchMetropoleInfluence: { x: '16.67%', y: '15.29%' },
} as const;

export const EGYPT_SCENARIO_TOKEN_ANCHORS = {
  Cairo: { x: '42.28%', y: '30.73%' },
  Alexandria: { x: '24.58%', y: '23.08%' },
  NileDelta: { x: '51.12%', y: '13.03%' },
  UpperEgypt: { x: '45.46%', y: '67.23%' },
  Suez: { x: '59.88%', y: '20.31%' },
  Sinai: { x: '69.88%', y: '23.63%' },
} as const;

export const IRAN_SCENARIO_TOKEN_ANCHORS = {
  Tehran: { x: '46.30%', y: '31.05%' },
  Kurdistan: { x: '21.98%', y: '26.15%' },
  Isfahan: { x: '45.62%', y: '59.52%' },
  Mashhad: { x: '70.01%', y: '38.68%' },
  Khuzestan: { x: '42.63%', y: '67.16%' },
  Balochistan: { x: '68.73%', y: '70.37%' },
} as const;

export const ALGERIA_SCENARIO_TOKEN_ANCHORS = {
  Algiers: { x: '53.44%', y: '7.51%' },
  KabylieMountains: { x: '59.87%', y: '7.57%' },
  Oran: { x: '42.61%', y: '15.05%' },
  SaharaSouth: { x: '53.58%', y: '55.50%' },
  TunisianBorder: { x: '69.13%', y: '12.31%' },
  FrenchMetropoleInfluence: { x: '16.67%', y: '15.29%' },
} as const;
