export { CORE_VERSION } from './version.ts';
export { asCoreId, createScopedId } from './ids.ts';
export { createGameState } from './createGame.ts';
export { dispatchCoreCommand } from './reducer.ts';
export { getPhaseId, getPlayer, getQueuedActions, getTrack, getZone } from './selectors.ts';
export { createRng, nextInt, nextRandom, shuffle } from './rng.ts';
export { stringifySave, serializeSave, deserializeSave } from './persistence/serialize.ts';
export { migrateEnvelope } from './persistence/migrate.ts';
export { validateCoreInvariants } from './validation/invariants.ts';
export { validateScenarioModule } from './validation/scenario.ts';
export { cloneCoreState, createBaseState, createDefaultDeck, createDefaultPlayer } from './validation/state.ts';
export { runSystemTurn } from './ai/runner.ts';
export { evaluateRuleExpression } from './rules/predicates.ts';
export { evaluateGameResult } from './rules/outcomes.ts';
export { calculateActionCosts, getActionResolutionContext, validateCommandAction } from './rules/runner.ts';
export { collectActionModifiers } from './rules/modifiers.ts';
export { BUILT_IN_CORE_COMMANDS } from './commands/types.ts';
export { createFixtureScenario } from './testing/fixtures.ts';
export { assertScenarioConformance } from './testing/conformance.ts';
export type * from './types.ts';
