import type { IconBaseShape, IconType } from './iconTypes.ts';

export const ICON_COLORS = {
  bodies: 'var(--color-accent)',
  comrades: 'var(--color-accent)',
  close: 'var(--color-text-muted)',
  copy: 'var(--color-text-muted)',
  evidence: 'var(--theme-evidence-blue)',
  defense: 'var(--color-success)',
  extraction: 'var(--theme-fossil-core)',
  pool: 'var(--theme-brass)',
  globalGaze: 'var(--theme-gaze-gold)',
  warMachine: 'var(--color-danger)',
  round: 'var(--theme-parchment)',
  modeLiberation: 'var(--theme-brass)',
  mandate: 'var(--color-accent-strong)',
  objective: 'var(--theme-parchment)',
  organize: 'var(--color-accent)',
  investigate: 'var(--theme-evidence-blue)',
  launchCampaign: 'var(--color-danger)',
  buildSolidarity: 'var(--color-success)',
  smuggleEvidence: 'var(--theme-brass)',
  internationalOutreach: 'var(--theme-gaze-gold)',
  defend: 'var(--color-success)',
  playCard: 'var(--front-culture)',
  advancePhase: 'var(--theme-brass)',
  frontWar: 'var(--front-war)',
  frontPlanet: 'var(--front-climate)',
  frontCage: 'var(--front-rights)',
  frontTruth: 'var(--front-speech-info)',
  frontHunger: 'var(--front-poverty)',
  frontFossil: 'var(--front-energy)',
  frontVoice: 'var(--front-culture)',
  frontWave: 'var(--front-wave, #5e8d80)',
  frontPatriarchy: 'var(--color-accent)',
  frontJustice: 'var(--theme-brass)',
  ledger: 'var(--color-accent-strong)',
  seat: 'var(--theme-brass)',
  home: 'var(--color-success)',
  save: 'var(--theme-evidence-blue)',
  language: 'var(--theme-gaze-gold)',
  crisis: 'var(--color-danger)',
  goViral: 'var(--theme-gaze-gold)',
  exposeLies: 'var(--theme-evidence-blue)',
  laborStrike: 'var(--color-accent)',
  coordinateDigital: 'var(--theme-evidence-blue)',
  burnVeil: 'var(--color-danger)',
  schoolgirlNetwork: 'var(--color-accent)',
  composeChant: 'var(--front-culture)',
  fundraise: 'var(--theme-brass)',
  mediaBlitz: 'var(--front-wave, #5e8d80)',
  sanctions: 'var(--theme-brass)',
} satisfies Record<IconType, string>;

export const ICON_BASE_SHAPES: Partial<Record<IconType, IconBaseShape>> = {
  bodies: 'circle',
  comrades: 'circle',
  evidence: 'circle',
  defense: 'circle',
  extraction: 'hex',
  pool: 'circle',
  globalGaze: 'diamond',
  warMachine: 'diamond',
  round: 'diamond',
  modeLiberation: 'rounded-rect',
  mandate: 'rounded-rect',
  objective: 'rounded-rect',
  crisis: 'hex',
  frontWar: 'rounded-rect',
  frontPlanet: 'rounded-rect',
  frontCage: 'rounded-rect',
  frontTruth: 'rounded-rect',
  frontHunger: 'rounded-rect',
  frontFossil: 'rounded-rect',
  frontVoice: 'rounded-rect',
  frontWave: 'rounded-rect',
  frontPatriarchy: 'rounded-rect',
  frontJustice: 'rounded-rect',
  home: 'circle',
  save: 'rounded-rect',
  language: 'circle',
};
