export type GameIconName =
  | 'comrades'
  | 'comrades'
  | 'crisis'
  | 'close'
  | 'copy'
  | 'evidence'
  | 'defense'
  | 'extraction'
  | 'extractionToken'
  | 'pool'
  | 'globalGaze'
  | 'warMachine'
  | 'round'
  | 'modeLiberation'
  | 'mandate'
  | 'objective'
  | 'organize'
  | 'investigate'
  | 'launchCampaign'
  | 'buildSolidarity'
  | 'smuggleEvidence'
  | 'internationalOutreach'
  | 'defend'
  | 'playCard'
  | 'advancePhase'
  | 'frontWar'
  | 'frontPlanet'
  | 'frontCage'
  | 'frontTruth'
  | 'frontHunger'
  | 'frontFossil'
  | 'frontVoice'
  | 'frontWave'
  | 'frontPatriarchy'
  | 'frontJustice'
  | 'ledger'
  | 'seat'
  | 'home'
  | 'save'
  | 'language'
  | 'goViral'
  | 'exposeLies'
  | 'laborStrike'
  | 'coordinateDigital'
  | 'burnVeil'
  | 'schoolgirlNetwork'
  | 'composeChant'
  | 'fundraise'
  | 'mediaBlitz'
  | 'sanctions'
  | 'check'
  | 'chevronDown'
  | 'contrast'
  | 'sparkles'
  | 'scrollText'
  | 'settings'
  | 'x';

export type IconType = GameIconName;

export type IconState = 'default' | 'hover' | 'selected' | 'critical' | 'disabled' | 'gain';
export type IconBaseShape = 'none' | 'circle' | 'hex' | 'diamond' | 'rounded-rect';
