import type { ResistanceCardDefinition } from '../../../engine/adapters/compat/types.ts';

export const resistanceCards: ResistanceCardDefinition[] = [
  {
    id: 'res_archive_leak',
    deck: 'resistance',
    type: 'action',
    name: 'Archive Leak',
    text: 'Acting faction gains 1 Evidence and raises Global Gaze by 1.',
    effects: [
      { type: 'modify_gaze', delta: 1 },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_mutual_aid_convoy',
    deck: 'resistance',
    type: 'action',
    name: 'Mutual Aid Convoy',
    text: 'Remove 1 Extraction Token from the target region.',
    effects: [{ type: 'remove_extraction', region: 'target_region', amount: 1 }],
  },
  {
    id: 'res_radio_uprising',
    deck: 'resistance',
    type: 'action',
    name: 'Radio Uprising',
    text: 'Advance Silenced Truth by 1 and add 1 Comrade to the target region for the acting faction.',
    effects: [
      { type: 'modify_domain', domain: 'SilencedTruth', delta: 1 },
      { type: 'add_bodies', region: 'target_region', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_strike_fund',
    deck: 'resistance',
    type: 'action',
    name: 'Strike Fund',
    text: 'Add 3 Comrades to the target region for the acting faction.',
    effects: [{ type: 'add_bodies', region: 'target_region', seat: 'acting_player', amount: 3 }],
  },
  {
    id: 'res_lawyers_brief',
    deck: 'resistance',
    type: 'action',
    name: 'Lawyers Brief',
    text: 'Advance Gilded Cage by 1 and reduce War Machine by 1 for the coalition.',
    effects: [
      { type: 'modify_domain', domain: 'GildedCage', delta: 1 },
      { type: 'modify_war_machine', delta: -1 },
    ],
  },
  {
    id: 'sup_arms_manifest',
    deck: 'resistance',
    type: 'support',
    name: 'Arms Shipment Manifest',
    text: 'Acting faction gets +2 on a War Machine campaign.',
    campaignBonus: 2,
    domainBonus: 'WarMachine',
  },
  {
    id: 'sup_watershed_maps',
    deck: 'resistance',
    type: 'support',
    name: 'Watershed Maps',
    text: 'Acting faction gets +2 on a Dying Planet campaign.',
    campaignBonus: 2,
    domainBonus: 'DyingPlanet',
  },
  {
    id: 'sup_prison_letters',
    deck: 'resistance',
    type: 'support',
    name: 'Prison Letters',
    text: 'Acting faction gets +2 on a Gilded Cage campaign.',
    campaignBonus: 2,
    domainBonus: 'GildedCage',
  },
  {
    id: 'sup_press_cables',
    deck: 'resistance',
    type: 'support',
    name: 'Press Cables',
    text: 'Acting faction gets +2 on a Silenced Truth campaign.',
    campaignBonus: 2,
    domainBonus: 'SilencedTruth',
  },
  {
    id: 'sup_debt_ledger',
    deck: 'resistance',
    type: 'support',
    name: 'Debt Ledger',
    text: 'Acting faction gets +2 on an Empty Stomach campaign.',
    campaignBonus: 2,
    domainBonus: 'EmptyStomach',
  },
  {
    id: 'sup_pipeline_routes',
    deck: 'resistance',
    type: 'support',
    name: 'Pipeline Routes',
    text: 'Acting faction gets +2 on a Fossil Grip campaign.',
    campaignBonus: 2,
    domainBonus: 'FossilGrip',
  },
  {
    id: 'sup_songbook',
    deck: 'resistance',
    type: 'support',
    name: 'Songbook',
    text: 'Acting faction gets +2 on a Stolen Voice campaign.',
    campaignBonus: 2,
    domainBonus: 'StolenVoice',
  },
];
