import { uiTokens } from '../ui/tokens/index.ts';
import type { ScenarioOverlayId, ThemeDefinition, ThemeOverlayDefinition } from './types.ts';

const { colors, motion, radius, shadows, spacing, typography, zIndex, layout } = uiTokens;

export const BASE_THEME: ThemeDefinition = {
  id: 'revolutionary-ink-paper',
  label: 'Revolutionary Ink & Paper',
  colors: {
    backgroundPrimary: colors.background.primary,
    backgroundSecondary: colors.background.secondary,
    backgroundPanel: colors.background.panel,
    backgroundElevated: colors.background.elevated,
    textPrimary: colors.text.primary,
    textSecondary: colors.text.secondary,
    textMuted: colors.text.muted,
    textInverted: colors.text.inverted,
    borderSubtle: colors.border.subtle,
    borderStrong: colors.border.strong,
    borderDanger: colors.border.danger,
    stateMovement: colors.state.movement,
    stateDanger: colors.state.danger,
    stateWarning: colors.state.warning,
    stateNeutral: colors.state.neutral,
    stateInfo: colors.state.info,
    domainWarMachine: colors.domain.warMachine,
    domainClimate: colors.domain.climate,
    domainFossil: colors.domain.fossil,
    domainJustice: colors.domain.justice,
    domainVoice: colors.domain.voice,
    domainHunger: colors.domain.hunger,
    domainPatriarchy: colors.domain.patriarchy,
    domainRevolution: colors.domain.revolution,
    heroTone: 'radial-gradient(120% 90% at 12% 8%, rgba(160, 59, 46, 0.2), transparent 58%), linear-gradient(140deg, rgba(46, 37, 28, 0.88), rgba(92, 80, 66, 0.76))',
    backgroundWash: 'rgba(46, 37, 28, 0.2)',
    selectionHighlight: 'rgba(160, 59, 46, 0.28)',
    tokenGlow: 'rgba(160, 59, 46, 0.28)',
    surfaceTint: 'rgba(160, 59, 46, 0.06)',
  },
  shadows: {
    subtle: shadows.subtle,
    medium: shadows.medium,
    strong: shadows.strong,
    focus: '0 0 0 3px rgba(160, 59, 46, 0.35)',
  },
  radius: {
    sm: radius.sm,
    md: radius.md,
    lg: radius.lg,
  },
  spacing: {
    xxs: spacing.xxs,
    xs: spacing.xs,
    sm: spacing.sm,
    md: spacing.md,
    lg: spacing.lg,
    xl: spacing.xl,
    xxl: spacing.xxl,
  },
  typography: {
    headline: typography.fontFamily.headline,
    body: typography.fontFamily.body,
    mono: typography.fontFamily.mono,
    sizeXs: typography.fontSize.xs,
    sizeSm: typography.fontSize.sm,
    sizeMd: typography.fontSize.md,
    sizeLg: typography.fontSize.lg,
    sizeXl: typography.fontSize.xl,
    sizeXxl: typography.fontSize.xxl,
    sizeHero: typography.fontSize.hero,
    weightRegular: String(typography.fontWeight.regular),
    weightMedium: String(typography.fontWeight.medium),
    weightBold: String(typography.fontWeight.bold),
    lineHeightTight: String(typography.lineHeight.tight),
    lineHeightNormal: String(typography.lineHeight.normal),
    lineHeightRelaxed: String(typography.lineHeight.relaxed),
  },
  motion: {
    fast: motion.fast,
    normal: motion.normal,
    slow: motion.slow,
    easing: motion.easing,
  },
  zIndex: {
    base: zIndex.base,
    panel: zIndex.panel,
    dropdown: zIndex.dropdown,
    modal: zIndex.modal,
    overlay: zIndex.overlay,
    toast: zIndex.toast,
  },
  layout: {
    iconXs: layout.icon.xs,
    iconSm: layout.icon.sm,
    iconMd: layout.icon.md,
    iconLg: layout.icon.lg,
    buttonPaddingY: layout.button.paddingY,
    buttonPaddingX: layout.button.paddingX,
    panelPadding: layout.panel.padding,
  },
};

export const SCENARIO_THEME_OVERLAYS: Record<ScenarioOverlayId, ThemeOverlayDefinition> = {
  'burnt-earth-resistance': {
    id: 'burnt-earth-resistance',
    label: 'Burnt Earth Resistance',
    overrides: {
      colors: {
        stateDanger: '#B46A3D',
        domainRevolution: '#B46A3D',
        heroTone: 'radial-gradient(120% 90% at 14% 8%, rgba(180, 106, 61, 0.24), transparent 56%), linear-gradient(140deg, rgba(54, 35, 23, 0.9), rgba(82, 58, 39, 0.8))',
        backgroundWash: 'rgba(72, 48, 31, 0.22)',
        selectionHighlight: 'rgba(180, 106, 61, 0.3)',
        tokenGlow: 'rgba(180, 106, 61, 0.3)',
        surfaceTint: 'rgba(180, 106, 61, 0.08)',
      },
    },
  },
  'rainforest-sovereignty': {
    id: 'rainforest-sovereignty',
    label: 'Rainforest Sovereignty',
    overrides: {
      colors: {
        stateMovement: '#2F704A',
        domainClimate: '#2F704A',
        heroTone: 'radial-gradient(120% 90% at 14% 8%, rgba(47, 112, 74, 0.28), transparent 58%), linear-gradient(140deg, rgba(18, 35, 28, 0.9), rgba(28, 45, 40, 0.84))',
        backgroundWash: 'rgba(22, 48, 34, 0.22)',
        selectionHighlight: 'rgba(47, 112, 74, 0.32)',
        tokenGlow: 'rgba(47, 112, 74, 0.36)',
        surfaceTint: 'rgba(47, 112, 74, 0.08)',
      },
    },
  },
  'dossier-of-the-disappeared': {
    id: 'dossier-of-the-disappeared',
    label: 'Dossier of the Disappeared',
    overrides: {
      colors: {
        stateDanger: '#7F3231',
        domainRevolution: '#7F3231',
        heroTone: 'radial-gradient(120% 90% at 14% 8%, rgba(127, 50, 49, 0.26), transparent 58%), linear-gradient(140deg, rgba(22, 24, 28, 0.92), rgba(38, 42, 35, 0.82))',
        backgroundWash: 'rgba(25, 27, 32, 0.24)',
        selectionHighlight: 'rgba(127, 50, 49, 0.34)',
        tokenGlow: 'rgba(127, 50, 49, 0.35)',
        surfaceTint: 'rgba(66, 72, 55, 0.08)',
      },
    },
  },
  'desert-horizon': {
    id: 'desert-horizon',
    label: 'Desert Horizon',
    overrides: {
      colors: {
        stateWarning: '#B46B3D',
        domainHunger: '#B46B3D',
        heroTone: 'radial-gradient(120% 90% at 14% 8%, rgba(180, 107, 61, 0.3), transparent 60%), linear-gradient(140deg, rgba(48, 35, 23, 0.88), rgba(37, 47, 60, 0.8))',
        backgroundWash: 'rgba(72, 48, 31, 0.22)',
        selectionHighlight: 'rgba(180, 107, 61, 0.34)',
        tokenGlow: 'rgba(180, 107, 61, 0.36)',
        surfaceTint: 'rgba(180, 107, 61, 0.08)',
      },
    },
  },
  'night-map-escalation': {
    id: 'night-map-escalation',
    label: 'Night Map Escalation',
    overrides: {
      colors: {
        stateWarning: '#D09138',
        domainJustice: '#D09138',
        heroTone: 'radial-gradient(120% 90% at 14% 8%, rgba(208, 145, 56, 0.22), transparent 58%), linear-gradient(140deg, rgba(16, 25, 44, 0.92), rgba(20, 31, 54, 0.85))',
        backgroundWash: 'rgba(14, 27, 48, 0.25)',
        selectionHighlight: 'rgba(208, 145, 56, 0.34)',
        tokenGlow: 'rgba(208, 145, 56, 0.36)',
        surfaceTint: 'rgba(27, 46, 74, 0.1)',
      },
    },
  },
};
