import type { ScenarioBoardDefinition } from '../../../engine/index.ts';
import { EGYPT_SCENARIO_MARKERS } from '../../shared/boards/generatedScenarioAnchors.ts';

export const tahrirBoard: ScenarioBoardDefinition = {
  assetPath: '/assets/scenarios/tahrir_square/egypt-location-map.svg',
  sourceViewBox: '0 0 1000 800',
  viewport: {
    canvasWidth: '100%',
    canvasHeight: '100%',
    canvasLeft: '0%',
    canvasTop: '0%',
  },
  svgIdConvention: 'GeoJSON-derived Egyptian scenario regions and city anchors.',
  regions: {
    Cairo: {
      regionId: 'Cairo',
      label: 'Cairo',
      marker: { ...EGYPT_SCENARIO_MARKERS.Cairo },
      tokenAnchor: { ...EGYPT_SCENARIO_MARKERS.Cairo },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 72,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '-18px', y: '-24px' },
      tooltipOffset: { x: '-92px', y: '-190px' },
      territoryTilt: '1deg',
      accent: '#8d6746',
      searchTerms: ['cairo', 'tahrir'],
      focusDomains: ['WarMachine', 'SilencedTruth', 'RevolutionaryWave'],
      anchorCoverage: ['cairo-shape'],
      interactionCoverage: ['cairo-shape'],
      svgCoverage: ['cairo-region'],
      note: 'Central organizing node and square-centered mass mobilization.',
    },
    Alexandria: {
      regionId: 'Alexandria',
      label: 'Alexandria',
      marker: { ...EGYPT_SCENARIO_MARKERS.Alexandria },
      tokenAnchor: { ...EGYPT_SCENARIO_MARKERS.Alexandria },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 68,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '-42px', y: '-20px' },
      tooltipOffset: { x: '-120px', y: '-186px' },
      territoryTilt: '-2deg',
      accent: '#9b7d5b',
      searchTerms: ['alexandria', 'mediterranean'],
      focusDomains: ['EmptyStomach', 'SilencedTruth', 'RevolutionaryWave'],
      anchorCoverage: ['alexandria-shape'],
      interactionCoverage: ['alexandria-shape'],
      svgCoverage: ['alexandria-region'],
      note: 'Mediterranean labor corridor and dockworker front.',
    },
    NileDelta: {
      regionId: 'NileDelta',
      label: 'Nile Delta',
      marker: { ...EGYPT_SCENARIO_MARKERS.NileDelta },
      tokenAnchor: { ...EGYPT_SCENARIO_MARKERS.NileDelta },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 70,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '20px', y: '-24px' },
      tooltipOffset: { x: '-82px', y: '-188px' },
      territoryTilt: '0deg',
      accent: '#ae8a61',
      searchTerms: ['nile', 'delta'],
      focusDomains: ['EmptyStomach', 'PatriarchalGrip', 'RevolutionaryWave'],
      anchorCoverage: ['nile-delta-shape'],
      interactionCoverage: ['nile-delta-shape'],
      svgCoverage: ['nile-delta-region'],
      note: 'Agrarian density and rural organizing corridor.',
    },
    UpperEgypt: {
      regionId: 'UpperEgypt',
      label: 'Upper Egypt',
      marker: { ...EGYPT_SCENARIO_MARKERS.UpperEgypt },
      tokenAnchor: { ...EGYPT_SCENARIO_MARKERS.UpperEgypt },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 74,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '18px', y: '-12px' },
      tooltipOffset: { x: '-88px', y: '-186px' },
      territoryTilt: '-1deg',
      accent: '#7b5c3d',
      searchTerms: ['upper egypt', 'south'],
      focusDomains: ['RevolutionaryWave', 'WarMachine', 'UnfinishedJustice'],
      anchorCoverage: ['upper-egypt-shape'],
      interactionCoverage: ['upper-egypt-shape'],
      svgCoverage: ['upper-egypt-region'],
      note: 'Neglected southern front shaped by repression and uneven reach.',
    },
    Suez: {
      regionId: 'Suez',
      label: 'Suez',
      marker: { ...EGYPT_SCENARIO_MARKERS.Suez },
      tokenAnchor: { ...EGYPT_SCENARIO_MARKERS.Suez },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 66,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '18px', y: '-20px' },
      tooltipOffset: { x: '-82px', y: '-188px' },
      territoryTilt: '2deg',
      accent: '#c18d5b',
      searchTerms: ['suez', 'canal'],
      focusDomains: ['WarMachine', 'EmptyStomach', 'RevolutionaryWave'],
      anchorCoverage: ['suez-shape'],
      interactionCoverage: ['suez-shape'],
      svgCoverage: ['suez-region'],
      note: 'Canal cities absorb the first shock of militarized retaliation.',
    },
    Sinai: {
      regionId: 'Sinai',
      label: 'Sinai',
      marker: { ...EGYPT_SCENARIO_MARKERS.Sinai },
      tokenAnchor: { ...EGYPT_SCENARIO_MARKERS.Sinai },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 68,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, bodies: { x: 0, y: 0.5 } },
      labelOffset: { x: '18px', y: '-18px' },
      tooltipOffset: { x: '-84px', y: '-188px' },
      territoryTilt: '4deg',
      accent: '#70513a',
      searchTerms: ['sinai'],
      focusDomains: ['WarMachine', 'UnfinishedJustice', 'PatriarchalGrip'],
      anchorCoverage: ['sinai-shape'],
      interactionCoverage: ['sinai-shape'],
      svgCoverage: ['sinai-region'],
      note: 'Peripheral zone where state violence and exclusion harden quickly.',
    },
  },
};
