import type {
  ActionDefinition,
  BeaconDefinition,
  CrisisCardDefinition,
  DomainDefinition,
  FactionDefinition,
  RegionDefinition,
  ResistanceCardDefinition,
  RulesetDefinition,
  SystemCardDefinition,
} from '../../engine/adapters/compat/types.ts';

const domains: DomainDefinition[] = [
  {
    id: 'RevolutionaryWave',
    name: 'National Uprising',
    description: 'The momentum of mass defiance across urban centers and villages.',
    initialProgress: 2,
  },
  {
    id: 'SilencedTruth',
    name: 'Public Testimony',
    description: 'The ability to speak colonial crimes to the world and coordinate the movement.',
    initialProgress: 1,
  },
  {
    id: 'EmptyStomach',
    name: 'Strike Capacity',
    description: 'Economic disruption through labor refusal and civil disobedience.',
    initialProgress: 0,
  },
  {
    id: 'GildedCage',
    name: 'Anti-Detention Pressure',
    description: 'The demand for the return of exiled leaders and the release of political detainees.',
    initialProgress: 1,
  },
  {
    id: 'StolenVoice',
    name: 'Mass Representation',
    description: 'Pluralist political representation that outgrows elite negotiation.',
    initialProgress: 0,
  },
  {
    id: 'UnfinishedJustice',
    name: 'Martyrs’ Reckoning',
    description: 'The collective memory of those fallen, fueling continued resistance.',
    initialProgress: 1,
  },
];

const regions: RegionDefinition[] = [
  {
    id: 'Cairo',
    name: 'Cairo',
    description: 'The administrative heart and center of the student uprising and women’s demonstrations.',
    strapline: 'The Center of Gravity.',
    vulnerability: { RevolutionaryWave: 3, SilencedTruth: 2, GildedCage: 2 },
  },
  {
    id: 'Alexandria',
    name: 'Alexandria',
    description: 'Port city with fierce labor presence and dockworker strikes against colonial logistics.',
    strapline: 'The Sea and the Docks.',
    vulnerability: { EmptyStomach: 3, RevolutionaryWave: 2, StolenVoice: 1 },
  },
  {
    id: 'DeltaRailCorridor',
    name: 'Delta Rail Corridor',
    description: 'The vital infrastructure link where railway workers sabotage colonial movement.',
    strapline: 'The Veins of the Nation.',
    vulnerability: { EmptyStomach: 2, RevolutionaryWave: 2, UnfinishedJustice: 2 },
  },
  {
    id: 'CanalZone',
    name: 'Canal Zone',
    description: 'British military strongholds and global transport artery under siege by local labor.',
    strapline: 'Imperial Chokehold.',
    vulnerability: { EmptyStomach: 2, GildedCage: 3, SilencedTruth: 1 },
  },
  {
    id: 'UpperEgypt',
    name: 'Upper Egypt',
    description: 'Autonomous districts and Assiut’s defiance, where state control is fragile.',
    strapline: 'The South Resists.',
    vulnerability: { StolenVoice: 3, UnfinishedJustice: 2, RevolutionaryWave: 1 },
  },
  {
    id: 'RuralVillages',
    name: 'Rural Villages',
    description: 'Fellahin networks organizing against crop seizure and punitive colonial levies.',
    strapline: 'The Soil and the People.',
    vulnerability: { EmptyStomach: 3, StolenVoice: 2, UnfinishedJustice: 1 },
  },
];

const factions: FactionDefinition[] = [
  {
    id: 'student_committees',
    name: 'Student Committees',
    shortName: 'Students',
    homeRegion: 'Cairo',
    passive: 'Investigate adds +1 Evidence in Cairo and campaigns for Public Testimony gain +1.',
    weakness: 'Mass arrests in Cairo cost 1 extra Comrade when War Machine is 6 or higher.',
    organizeBonus: 1,
    investigateBonus: 1,
    defenseBonus: 0,
    campaignDomainBonus: 'SilencedTruth',
    campaignBonus: 1,
    outreachPenalty: 0,
    mandate: {
      id: 'mandate_egy_students',
      title: 'Campus Sovereignty',
      description: 'End with Public Testimony at 6 or more and Cairo at 2 or fewer Extraction Tokens.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'domain_progress', domain: 'SilencedTruth' }, op: '>=', right: 6 },
          { kind: 'compare', left: { type: 'region_extraction', region: 'Cairo' }, op: '<=', right: 2 },
        ],
      },
    },
  },
  {
    id: 'railway_workers',
    name: 'Railway Workers',
    shortName: 'Railway',
    homeRegion: 'DeltaRailCorridor',
    passive: 'Campaigns for Strike Capacity gain +1 and actions in Delta Rail Corridor cost 1 fewer Comrade.',
    weakness: 'Railway lockouts set 1 less Defense in the Corridor.',
    organizeBonus: 1,
    investigateBonus: 0,
    defenseBonus: 1,
    campaignDomainBonus: 'EmptyStomach',
    campaignBonus: 1,
    outreachPenalty: 0,
    mandate: {
      id: 'mandate_egy_railway',
      title: 'Halt the Extraction',
      description: 'End with Strike Capacity at 5 or more and Delta Rail Corridor at 1 or fewer Extraction Tokens.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'domain_progress', domain: 'EmptyStomach' }, op: '>=', right: 5 },
          { kind: 'compare', left: { type: 'region_extraction', region: 'DeltaRailCorridor' }, op: '<=', right: 1 },
        ],
      },
    },
  },
  {
    id: 'womens_action_circles',
    name: 'Women’s Action Circles',
    shortName: 'Women',
    homeRegion: 'Cairo',
    passive: '+1 to all National Uprising campaigns and Organizing in Cairo/Alexandria adds +1 Comrade.',
    weakness: 'Repression of public demonstrations reduces National Uprising by 1.',
    organizeBonus: 1,
    investigateBonus: 0,
    defenseBonus: 0,
    campaignDomainBonus: 'RevolutionaryWave',
    campaignBonus: 1,
    outreachPenalty: 0,
    mandate: {
      id: 'mandate_egy_women',
      title: 'Public Defiance',
      description: 'End with National Uprising at 7 or more and Alexandria at 2 or fewer Extraction Tokens.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'domain_progress', domain: 'RevolutionaryWave' }, op: '>=', right: 7 },
          { kind: 'compare', left: { type: 'region_extraction', region: 'Alexandria' }, op: '<=', right: 2 },
        ],
      },
    },
  },
  {
    id: 'provincial_organizers',
    name: 'Provincial Organizers',
    shortName: 'Provinces',
    homeRegion: 'UpperEgypt',
    passive: 'Organize adds +1 Comrade in Upper Egypt/Rural Villages and outreach is free.',
    weakness: 'Military provincial reprisals remove 2 Comrades instead of 1.',
    organizeBonus: 1,
    investigateBonus: 0,
    defenseBonus: 1,
    campaignDomainBonus: 'StolenVoice',
    campaignBonus: 1,
    outreachPenalty: 0,
    mandate: {
      id: 'mandate_egy_provinces',
      title: 'Village Sovereignty',
      description: 'End with Mass Representation at 5 or more and Rural Villages at 1 or fewer Extraction Tokens.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'domain_progress', domain: 'StolenVoice' }, op: '>=', right: 5 },
          { kind: 'compare', left: { type: 'region_extraction', region: 'RuralVillages' }, op: '<=', right: 1 },
        ],
      },
    },
  },
];

const beacons: BeaconDefinition[] = [
  {
    id: 'beacon_egy_student_strike',
    title: 'March 9: The Student Strike',
    description: 'Students at Al-Azhar and schools across Cairo trigger the mass uprising.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'domain_progress', domain: 'RevolutionaryWave' }, op: '>=', right: 3 },
        { kind: 'compare', left: { type: 'region_extraction', region: 'Cairo' }, op: '<=', right: 2 },
      ],
    },
  },
  {
    id: 'beacon_egy_railway_sabotage',
    title: 'Delta Rail Blockade',
    description: 'Railway lines are severed, preventing British military reinforcements.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'domain_progress', domain: 'EmptyStomach' }, op: '>=', right: 4 },
        { kind: 'compare', left: { type: 'region_extraction', region: 'DeltaRailCorridor' }, op: '<=', right: 1 },
      ],
    },
  },
  {
    id: 'beacon_egy_womens_march',
    title: 'March 16: Women’s Demonstration',
    description: 'Women take the lead in public defiance, shattering gendered colonial constraints.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'domain_progress', domain: 'RevolutionaryWave' }, op: '>=', right: 5 },
        { kind: 'compare', left: { type: 'scenario_flag', flag: 'womensMobilization' }, op: '==', right: 1 },
      ],
    },
  },
  {
    id: 'beacon_egy_funerary_uprising',
    title: 'The Funerary Uprising',
    description: 'Funeral processions for fallen comrades become massive political mobilizations.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'domain_progress', domain: 'UnfinishedJustice' }, op: '>=', right: 4 },
        { kind: 'compare', left: { type: 'global_gaze' }, op: '>=', right: 10 },
      ],
    },
  },
  {
    id: 'beacon_egy_alexandria_dock_strike',
    title: 'Alexandria Labor Solidarity',
    description: 'Dockworkers and factory unions halt the logistics of occupation.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'domain_progress', domain: 'EmptyStomach' }, op: '>=', right: 6 },
        { kind: 'compare', left: { type: 'region_extraction', region: 'Alexandria' }, op: '<=', right: 1 },
      ],
    },
  },
  {
    id: 'beacon_egy_provincial_defection',
    title: 'Assiut Defiance',
    description: 'Major provincial centers declare liberation, forcing the British to retreat.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'domain_progress', domain: 'StolenVoice' }, op: '>=', right: 5 },
        { kind: 'compare', left: { type: 'region_extraction', region: 'UpperEgypt' }, op: '<=', right: 1 },
      ],
    },
  },
];

const actions: ActionDefinition[] = [
  {
    id: 'organize',
    name: 'Organize',
    description: 'Roll 1d6 Comrades into a region, with movement bonuses at home.',
    resolvePriority: 100,
    needsRegion: true,
  },
  {
    id: 'investigate',
    name: 'Investigate',
    description: 'Generate Evidence and draw resistance cards.',
    resolvePriority: 120,
    needsRegion: true,
  },
  {
    id: 'launch_campaign',
    name: 'Launch Campaign',
    description: 'Commit Comrades and Evidence to a 2d6 campaign against a Domain in a region.',
    resolvePriority: 500,
    needsRegion: true,
    needsDomain: true,
    needsComrades: true,
    needsEvidence: true,
    needsCard: true,
    cardType: 'support',
  },
  {
    id: 'build_solidarity',
    name: 'Build Solidarity',
    description: 'Spend 3 Comrades in-region to advance a Domain without a roll.',
    resolvePriority: 300,
    needsRegion: true,
    needsDomain: true,
  },
  {
    id: 'smuggle_evidence',
    name: 'Smuggle Evidence',
    description: 'Move Evidence to another faction through a risky corridor.',
    resolvePriority: 180,
    needsRegion: true,
    needsTargetSeat: true,
  },
  {
    id: 'international_outreach',
    name: 'Global Appeal',
    description: 'Spend Evidence to raise Global Gaze.',
    resolvePriority: 200,
  },
  {
    id: 'defend',
    name: 'Defend',
    description: 'Convert Comrades into a one-round Defense Rating against the next intervention.',
    resolvePriority: 260,
    needsRegion: true,
    needsComrades: true,
  },
  {
    id: 'play_card',
    name: 'Play Card',
    description: 'Resolve an action card from hand for direct tactical impact.',
    resolvePriority: 220,
    needsRegion: true,
    needsCard: true,
    cardType: 'action',
  },
];

const resistanceCards: ResistanceCardDefinition[] = [
  {
    id: 'res_egy_1919_committee_communcation',
    deck: 'resistance',
    type: 'action',
    name: 'Secret Committee Communication',
    text: 'Draw an extra card.',
    effects: [{ type: 'draw_resistance', seat: 'acting_player', count: 1 }],
  },
];

const crisisCards: CrisisCardDefinition[] = [
  {
    id: 'crisis_egy_1919_mass_detention',
    deck: 'crisis',
    name: 'Mass Arrests in Cairo',
    text: 'Lose 2 Comrades in Cairo.',
    effects: [{ type: 'remove_comrades', region: 'Cairo', seat: 0, amount: 2 }],
  },
];

const systemCards: SystemCardDefinition[] = [
  {
    id: 'system_egy_1919_allenby_ultimatum',
    deck: 'system',
    name: 'Allenby Ultimatum',
    text: 'Add 2 Extraction Tokens to Cairo.',
    onReveal: [{ type: 'add_extraction', region: 'Cairo', amount: 2 }],
  },
];

export const compatRuleset: RulesetDefinition = {
  id: 'egypt_1919_revolution',
  name: '1919 — EGYPT RISES',
  description: '"Bread, Nation, and the Streets."',
  introduction: 'The 1919 uprising is a mass coalition struggle. Students, railway workers, and women’s Action Circles must hold Cairo and the provinces while British occupation attempts to suppress popular mobilization through detention and martial law.',
  board: {
    assetPath: '/assets/scenarios/egypt_1919/egypt-1919-map.svg',
    sourceViewBox: '0 0 1000 800',
    viewport: {
      canvasWidth: '100%',
      canvasHeight: '100%',
      canvasLeft: '0%',
      canvasTop: '0%',
    },
    regions: {
      Cairo: {
        regionId: 'Cairo',
        label: 'Cairo',
        marker: { x: '500', y: '400' },
        tokenAnchor: { x: '500', y: '420' },
        anchorBias: { x: 0, y: 0 },
        clusterRadius: 70,
        labelOffsetY: -15,
        opticalCenteringByTokenType: { extraction: { x: 0, y: 0 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0 } },
        labelOffset: { x: '0', y: '0' },
        tooltipOffset: { x: '0', y: '0' },
        territoryTilt: '0',
        accent: '#C4A484',
        searchTerms: ['cairo', 'capital'],
        focusDomains: ['RevolutionaryWave', 'SilencedTruth', 'GildedCage'],
        anchorCoverage: [],
        interactionCoverage: [],
        svgCoverage: [],
        note: 'The heart of the uprising.',
      },
      Alexandria: {
        regionId: 'Alexandria',
        label: 'Alexandria',
        marker: { x: '300', y: '300' },
        tokenAnchor: { x: '300', y: '320' },
        anchorBias: { x: 0, y: 0 },
        clusterRadius: 70,
        labelOffsetY: -15,
        opticalCenteringByTokenType: { extraction: { x: 0, y: 0 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0 } },
        labelOffset: { x: '0', y: '0' },
        tooltipOffset: { x: '0', y: '0' },
        territoryTilt: '0',
        accent: '#7BAFD4',
        searchTerms: ['alexandria', 'port', 'labor'],
        focusDomains: ['EmptyStomach', 'RevolutionaryWave', 'StolenVoice'],
        anchorCoverage: [],
        interactionCoverage: [],
        svgCoverage: [],
        note: 'Dockworker resistance.',
      },
      DeltaRailCorridor: {
        regionId: 'DeltaRailCorridor',
        label: 'Delta Rail Corridor',
        marker: { x: '450', y: '350' },
        tokenAnchor: { x: '450', y: '370' },
        anchorBias: { x: 0, y: 0 },
        clusterRadius: 70,
        labelOffsetY: -15,
        opticalCenteringByTokenType: { extraction: { x: 0, y: 0 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0 } },
        labelOffset: { x: '0', y: '0' },
        tooltipOffset: { x: '0', y: '0' },
        territoryTilt: '0',
        accent: '#8B4513',
        searchTerms: ['delta', 'railway', 'sabotage'],
        focusDomains: ['EmptyStomach', 'RevolutionaryWave', 'UnfinishedJustice'],
        anchorCoverage: [],
        interactionCoverage: [],
        svgCoverage: [],
        note: 'Sabotage of imperial movement.',
      },
      CanalZone: {
        regionId: 'CanalZone',
        label: 'Canal Zone',
        marker: { x: '650', y: '380' },
        tokenAnchor: { x: '650', y: '400' },
        anchorBias: { x: 0, y: 0 },
        clusterRadius: 70,
        labelOffsetY: -15,
        opticalCenteringByTokenType: { extraction: { x: 0, y: 0 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0 } },
        labelOffset: { x: '0', y: '0' },
        tooltipOffset: { x: '0', y: '0' },
        territoryTilt: '0',
        accent: '#556B2F',
        searchTerms: ['canal', 'suez', 'military'],
        focusDomains: ['EmptyStomach', 'GildedCage', 'SilencedTruth'],
        anchorCoverage: [],
        interactionCoverage: [],
        svgCoverage: [],
        note: 'Imperial chokehold.',
      },
      UpperEgypt: {
        regionId: 'UpperEgypt',
        label: 'Upper Egypt',
        marker: { x: '550', y: '650' },
        tokenAnchor: { x: '550', y: '670' },
        anchorBias: { x: 0, y: 0 },
        clusterRadius: 70,
        labelOffsetY: -15,
        opticalCenteringByTokenType: { extraction: { x: 0, y: 0 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0 } },
        labelOffset: { x: '0', y: '0' },
        tooltipOffset: { x: '0', y: '0' },
        territoryTilt: '0',
        accent: '#C18D5B',
        searchTerms: ['south', 'assiut', 'sovereignty'],
        focusDomains: ['StolenVoice', 'UnfinishedJustice', 'RevolutionaryWave'],
        anchorCoverage: [],
        interactionCoverage: [],
        svgCoverage: [],
        note: 'Provincial defience.',
      },
      RuralVillages: {
        regionId: 'RuralVillages',
        label: 'Rural Villages',
        marker: { x: '400', y: '500' },
        tokenAnchor: { x: '400', y: '520' },
        anchorBias: { x: 0, y: 0 },
        clusterRadius: 70,
        labelOffsetY: -15,
        opticalCenteringByTokenType: { extraction: { x: 0, y: 0 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0 } },
        labelOffset: { x: '0', y: '0' },
        tooltipOffset: { x: '0', y: '0' },
        territoryTilt: '0',
        accent: '#556B2F',
        searchTerms: ['rural', 'villages', 'fellahin'],
        focusDomains: ['EmptyStomach', 'StolenVoice', 'UnfinishedJustice'],
        anchorCoverage: [],
        interactionCoverage: [],
        svgCoverage: [],
        note: 'Village networks.',
      },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any,
  },
  regions,
  domains,
  factions,
  beacons,
  actions,
  resistanceCards,
  crisisCards,
  systemCards,
  liberationThreshold: 5,
  suddenDeathRound: 10,
  victoryGate: {
    minRoundBeforeVictory: 3,
  },
  victoryScoring: {
    mode: 'score',
    threshold: 65,
    survivalScorePerRound: 0.5,
    components: [
      {
        id: 'publicVictory',
        label: 'Public Victory',
        weight: 60,
        type: 'binaryCondition',
        source: {
          type: 'publicVictory',
        },
      },
      {
        id: 'mandates',
        label: 'Secret Mandates',
        weight: 40,
        type: 'binaryCondition',
        source: {
          type: 'mandates',
        },
      },
    ],
    mandatesAsScore: {
      enabled: true,
      weight: 40,
      mandateProgressMode: 'binary',
    },
    outcomeBands: [
      { id: 'defeat', min: 0, max: 34.99 },
      { id: 'continuation', min: 35, max: 59.99 },
      { id: 'win_with_consequence', min: 60, max: 79.99 },
      { id: 'breakthrough', min: 80, max: 100 },
    ],
  },
  setup: {
    globalGaze: 4,
    northernWarMachine: 5,
    extractionPool: 64,
    extractionSeeds: {
      Cairo: 2,
      Alexandria: 1,
      DeltaRailCorridor: 1,
      CanalZone: 2,
      UpperEgypt: 1,
      RuralVillages: 1,
    },
  },
  customTracks: [],
  specialRules: [
    {
      id: 'railway_sabotage',
      label: 'Railway Sabotage',
      description: 'Successful campaigns in Delta Rail Corridor reduce System Escalation speed.',
    },
    {
      id: 'funerary_mobilization',
      label: 'Funerary Mobilization',
      description: 'Losing Comrades in urban zones adds +1 to Martyrs’ Reckoning progress.',
    },
  ],
  scenarioFlags: ['womensMobilization', 'railSabotaged'],
  scenarioHooks: {
    urbanCampaignRegions: ['Cairo', 'Alexandria'],
  },
  victoryConditions: {
    liberation: {
      kind: 'all',
      conditions: [
        { kind: 'every_region_extraction_at_most', count: 1 },
        { kind: 'compare', left: { type: 'domain_progress', domain: 'RevolutionaryWave' }, op: '>=', right: 6 },
        { kind: 'compare', left: { type: 'domain_progress', domain: 'StolenVoice' }, op: '>=', right: 5 },
      ],
    },
  },
};

export {
  actions,
  beacons,
  crisisCards,
  domains,
  factions,
  regions,
  resistanceCards,
  systemCards,
};

export default compatRuleset;
