import type {
  ActionDefinition,
  CardDefinition,
  CharterClauseDefinition,
  FrontDefinition,
  InstitutionDefinition,
  PackDefinition,
  RegionDefinition,
  RoleDefinition,
  RuleDefinition,
} from '../../engine/types.ts';

const fronts: FrontDefinition[] = [
  {
    id: 'WAR',
    name: 'War',
    initial: { pressure: 6, protection: 2, impact: 4 },
    collapseConditions: [
      { kind: 'compare', left: { type: 'front_stat', front: 'WAR', stat: 'impact' }, op: '>=', right: 10 },
      {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'front_stat', front: 'WAR', stat: 'pressure' }, op: '>=', right: 9 },
          { kind: 'compare', left: { type: 'front_stat', front: 'WAR', stat: 'protection' }, op: '<=', right: 1 },
        ],
      },
    ],
    couplingRuleIds: ['coupling_war_displacement', 'coupling_war_threat'],
  },
  {
    id: 'CLIMATE',
    name: 'Climate',
    initial: { pressure: 3, protection: 3, impact: 2 },
    collapseConditions: [
      { kind: 'compare', left: { type: 'front_stat', front: 'CLIMATE', stat: 'impact' }, op: '>=', right: 10 },
      {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'front_stat', front: 'CLIMATE', stat: 'pressure' }, op: '>=', right: 9 },
          { kind: 'compare', left: { type: 'front_stat', front: 'CLIMATE', stat: 'protection' }, op: '<=', right: 1 },
        ],
      },
    ],
    couplingRuleIds: [],
  },
  {
    id: 'RIGHTS',
    name: 'Human Rights',
    initial: { pressure: 5, protection: 3, impact: 3 },
    collapseConditions: [
      { kind: 'compare', left: { type: 'front_stat', front: 'RIGHTS', stat: 'impact' }, op: '>=', right: 10 },
      {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'front_stat', front: 'RIGHTS', stat: 'pressure' }, op: '>=', right: 9 },
          { kind: 'compare', left: { type: 'front_stat', front: 'RIGHTS', stat: 'protection' }, op: '<=', right: 1 },
        ],
      },
    ],
    couplingRuleIds: [],
  },
  {
    id: 'SPEECH_INFO',
    name: 'Speech & Information',
    initial: { pressure: 4, protection: 4, impact: 2 },
    collapseConditions: [
      { kind: 'compare', left: { type: 'front_stat', front: 'SPEECH_INFO', stat: 'impact' }, op: '>=', right: 10 },
      {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'front_stat', front: 'SPEECH_INFO', stat: 'pressure' }, op: '>=', right: 9 },
          { kind: 'compare', left: { type: 'front_stat', front: 'SPEECH_INFO', stat: 'protection' }, op: '<=', right: 1 },
        ],
      },
    ],
    couplingRuleIds: [],
  },
  {
    id: 'POVERTY',
    name: 'Poverty',
    initial: { pressure: 5, protection: 2, impact: 4 },
    collapseConditions: [
      { kind: 'compare', left: { type: 'front_stat', front: 'POVERTY', stat: 'impact' }, op: '>=', right: 10 },
      {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'front_stat', front: 'POVERTY', stat: 'pressure' }, op: '>=', right: 9 },
          { kind: 'compare', left: { type: 'front_stat', front: 'POVERTY', stat: 'protection' }, op: '<=', right: 1 },
        ],
      },
    ],
    couplingRuleIds: ['coupling_poverty_disinfo'],
  },
  {
    id: 'ENERGY',
    name: 'Energy',
    initial: { pressure: 3, protection: 4, impact: 2 },
    collapseConditions: [
      { kind: 'compare', left: { type: 'front_stat', front: 'ENERGY', stat: 'impact' }, op: '>=', right: 10 },
      {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'front_stat', front: 'ENERGY', stat: 'pressure' }, op: '>=', right: 9 },
          { kind: 'compare', left: { type: 'front_stat', front: 'ENERGY', stat: 'protection' }, op: '<=', right: 1 },
        ],
      },
    ],
    couplingRuleIds: [],
  },
  {
    id: 'CULTURE',
    name: 'Art & Culture',
    initial: { pressure: 2, protection: 5, impact: 1 },
    collapseConditions: [
      { kind: 'compare', left: { type: 'front_stat', front: 'CULTURE', stat: 'impact' }, op: '>=', right: 10 },
      {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'front_stat', front: 'CULTURE', stat: 'pressure' }, op: '>=', right: 9 },
          { kind: 'compare', left: { type: 'front_stat', front: 'CULTURE', stat: 'protection' }, op: '<=', right: 1 },
        ],
      },
    ],
    couplingRuleIds: [],
  },
];

const regions: RegionDefinition[] = [
  {
    id: 'MENA',
    name: 'MENA',
    vulnerability: { WAR: 3, RIGHTS: 3, CLIMATE: 1, SPEECH_INFO: 1 },
  },
  {
    id: 'SubSaharanAfrica',
    name: 'Sub-Saharan Africa',
    vulnerability: { CLIMATE: 2, POVERTY: 3, ENERGY: 2 },
  },
  {
    id: 'SouthAsia',
    name: 'South Asia',
    vulnerability: { CLIMATE: 3, POVERTY: 2, ENERGY: 2 },
  },
  {
    id: 'SoutheastAsia',
    name: 'Southeast Asia',
    vulnerability: { CLIMATE: 2, SPEECH_INFO: 2, POVERTY: 1 },
  },
  {
    id: 'LatinAmerica',
    name: 'Latin America',
    vulnerability: { POVERTY: 2, SPEECH_INFO: 2, CULTURE: 1 },
  },
  {
    id: 'Europe',
    name: 'Europe',
    vulnerability: { SPEECH_INFO: 1, RIGHTS: 1 },
  },
  {
    id: 'NorthAmerica',
    name: 'North America',
    vulnerability: { SPEECH_INFO: 1, RIGHTS: 1 },
  },
  {
    id: 'PacificIslands',
    name: 'Pacific Islands',
    vulnerability: { CLIMATE: 3, ENERGY: 1 },
  },
];

const institutions: InstitutionDefinition[] = [
  {
    id: 'MutualAidHub',
    name: 'Mutual Aid Hub',
    description: 'Generates solidarity when displacement is present.',
    roleId: 'organizer',
  },
  {
    id: 'IndependentMediaNetwork',
    name: 'Independent Media Network',
    description: 'Converts pressure into truth windows and removes disinfo.',
    roleId: 'investigative_journalist',
  },
  {
    id: 'LegalClinic',
    name: 'Legal Clinic',
    description: 'Blocks the first control lock applied each round.',
    roleId: 'human_rights_lawyer',
  },
  {
    id: 'CommunityMicrogrid',
    name: 'Community Microgrid',
    description: 'Absorbs one climate or energy deterioration hit each round.',
    roleId: 'climate_energy_planner',
  },
];

const actions: ActionDefinition[] = [
  {
    id: 'rest_and_care',
    roleId: 'shared',
    name: 'Rest & Care',
    description: 'Recover burnout and steady the coalition.',
    targetKind: 'NONE',
    resolvePriority: 100,
    effects: [
      { type: 'modify_track', target: { type: 'player_burnout', player: 'acting_player' }, delta: -2 },
      { type: 'log', emoji: '🧠', message: 'Rest & Care eases burnout.' },
    ],
  },
  {
    id: 'cultural_resonance',
    roleId: 'shared',
    name: 'Cultural Resonance',
    description: 'Draw and resolve a culture card in a chosen region.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 100,
    cultureAction: true,
    publicAction: true,
    resourceCosts: { solidarity: 1 },
    effects: [
      { type: 'draw_from_deck', deck: 'culture', count: 1 },
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'mutual_aid_network',
    roleId: 'organizer',
    name: 'Mutual Aid Network',
    description: 'Build solidarity infrastructure and ease displacement.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 400,
    publicAction: true,
    resourceCosts: { solidarity: 1 },
    effects: [
      { type: 'ensure_institution', region: 'target_region', institution: 'MutualAidHub' },
      { type: 'modify_front_stat', front: 'POVERTY', stat: 'pressure', delta: -1, clamp: { min: 0, max: 10 } },
      {
        type: 'conditional',
        if: { kind: 'tokenCount', region: 'target_region', token: 'displacement', op: '>=', count: 1 },
        then: [{ type: 'remove_token', region: 'target_region', token: 'displacement', count: 1 }],
      },
    ],
  },
  {
    id: 'community_mobilization',
    roleId: 'organizer',
    name: 'Community Mobilization',
    description: 'Turn visibility into solidarity.',
    targetKind: 'NONE',
    resolvePriority: 600,
    publicAction: true,
    effects: [
      { type: 'gain_resource', resource: 'solidarity', amount: 2 },
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'safe_passage',
    roleId: 'organizer',
    name: 'Safe Passage',
    description: 'Open civilian corridors or relocate people out of immediate harm.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 200,
    publicAction: true,
    effects: [
      {
        type: 'conditional',
        if: { kind: 'hasLock', region: 'target_region', lock: 'AidAccess' },
        then: [{ type: 'remove_lock', region: 'target_region', lock: 'AidAccess' }],
        else: [
          {
            type: 'conditional',
            if: { kind: 'tokenCount', region: 'target_region', token: 'displacement', op: '>=', count: 1 },
            then: [{ type: 'remove_token', region: 'target_region', token: 'displacement', count: 1 }],
          },
        ],
      },
    ],
  },
  {
    id: 'mass_mobilization',
    roleId: 'organizer',
    name: 'Mass Mobilization',
    description: 'A difficult breakthrough that pushes back hard on one front.',
    targetKind: 'FRONT',
    targetLabel: 'Front',
    resolvePriority: 700,
    publicAction: true,
    burnoutCost: 2,
    resourceCosts: { solidarity: 1 },
    effects: [
      { type: 'modify_front_stat', front: 'target_front', stat: 'pressure', delta: -2, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'field_investigation',
    roleId: 'investigative_journalist',
    name: 'Field Investigation',
    description: 'Gather evidence and open a truth window in the target region.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 300,
    journalismAction: true,
    effects: [
      { type: 'gain_resource', resource: 'evidence', amount: 2 },
      { type: 'set_flag', scope: 'round', key: 'truth_window:target_region', value: true },
      { type: 'ensure_institution', region: 'target_region', institution: 'IndependentMediaNetwork' },
    ],
  },
  {
    id: 'counter_disinfo',
    roleId: 'investigative_journalist',
    name: 'Counter Disinfo',
    description: 'Remove disinfo and strengthen truth windows.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 300,
    journalismAction: true,
    antiDisinfoAction: true,
    resourceCosts: { evidence: 1 },
    effects: [
      { type: 'remove_token', region: 'target_region', token: 'disinfo', count: 1 },
      {
        type: 'conditional',
        if: { kind: 'flagIs', scope: 'round', key: 'truth_window:target_region', value: true },
        then: [{ type: 'remove_token', region: 'target_region', token: 'disinfo', count: 1 }],
      },
    ],
  },
  {
    id: 'truth_window',
    roleId: 'investigative_journalist',
    name: 'Truth Window',
    description: 'Create a bypass for culture and journalism in a censored region.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 300,
    journalismAction: true,
    bypassesCensorship: true,
    resourceCosts: { evidence: 1 },
    effects: [{ type: 'set_flag', scope: 'round', key: 'truth_window:target_region', value: true }],
  },
  {
    id: 'global_expose',
    roleId: 'investigative_journalist',
    name: 'Global Expose',
    description: 'Breakthrough reporting strips away disinfo across the map.',
    targetKind: 'NONE',
    resolvePriority: 700,
    journalismAction: true,
    antiDisinfoAction: true,
    burnoutCost: 2,
    effects: [
      { type: 'remove_token', region: 'ANY', token: 'disinfo', count: 1 },
      { type: 'modify_front_stat', front: 'SPEECH_INFO', stat: 'pressure', delta: -1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'emergency_injunction',
    roleId: 'human_rights_lawyer',
    name: 'Emergency Injunction',
    description: 'Raise rights protection through immediate remedy work.',
    targetKind: 'NONE',
    resolvePriority: 400,
    resourceCosts: { evidence: 2 },
    effects: [{ type: 'modify_front_stat', front: 'RIGHTS', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } }],
  },
  {
    id: 'clear_aid_corridor',
    roleId: 'human_rights_lawyer',
    name: 'Clear Aid Corridor',
    description: 'Remove access and surveillance locks from a region.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 200,
    effects: [
      { type: 'remove_lock', region: 'target_region', lock: 'AidAccess' },
      { type: 'remove_lock', region: 'target_region', lock: 'Surveillance' },
    ],
  },
  {
    id: 'remedy_dossier',
    roleId: 'human_rights_lawyer',
    name: 'Remedy Dossier',
    description: 'Turn testimony into remedy pressure and local legal cover.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 400,
    resourceCosts: { evidence: 1 },
    effects: [
      { type: 'add_charter_progress', amount: 1 },
      { type: 'ensure_institution', region: 'target_region', institution: 'LegalClinic' },
      {
        type: 'conditional',
        if: { kind: 'compare', left: { type: 'front_stat', front: 'WAR', stat: 'pressure' }, op: '>=', right: 7 },
        then: [{ type: 'modify_front_stat', front: 'RIGHTS', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } }],
      },
    ],
  },
  {
    id: 'international_tribunal',
    roleId: 'human_rights_lawyer',
    name: 'International Tribunal',
    description: 'Escalate accountability into ratification momentum.',
    targetKind: 'NONE',
    resolvePriority: 700,
    burnoutCost: 2,
    effects: [{ type: 'ratify_first_available_charter', fallbackProgress: 2 }],
  },
  {
    id: 'build_microgrid',
    roleId: 'climate_energy_planner',
    name: 'Build Microgrid',
    description: 'Build local energy resilience in a vulnerable region.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 500,
    resourceCosts: { capacity: 2 },
    effects: [
      { type: 'ensure_institution', region: 'target_region', institution: 'CommunityMicrogrid' },
      { type: 'modify_front_stat', front: 'ENERGY', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'disaster_preparedness',
    roleId: 'climate_energy_planner',
    name: 'Disaster Preparedness',
    description: 'Blunt climate harm and prepare for displacement shocks.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 400,
    effects: [
      { type: 'modify_front_stat', front: 'CLIMATE', stat: 'impact', delta: -1, clamp: { min: 0, max: 10 } },
      { type: 'set_flag', scope: 'round', key: 'prevent_displacement:target_region', value: true },
    ],
  },
  {
    id: 'resilience_retrofit',
    roleId: 'climate_energy_planner',
    name: 'Resilience Retrofit',
    description: 'Reduce energy pressure and buffer poverty spillover.',
    targetKind: 'REGION',
    targetLabel: 'Region',
    resolvePriority: 500,
    resourceCosts: { capacity: 1 },
    effects: [
      { type: 'modify_front_stat', front: 'ENERGY', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'POVERTY', stat: 'pressure', delta: -1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'rapid_decarbonization',
    roleId: 'climate_energy_planner',
    name: 'Rapid Decarbonization',
    description: 'Force a temporary reversal of the climate clock.',
    targetKind: 'NONE',
    resolvePriority: 700,
    burnoutCost: 2,
    effects: [
      { type: 'modify_track', target: { type: 'temperature' }, delta: -1, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'ENERGY', stat: 'pressure', delta: -2, clamp: { min: 0, max: 10 } },
    ],
  },
];

const roles: RoleDefinition[] = [
  {
    id: 'organizer',
    name: 'Community Organizer',
    shortName: 'Organizer',
    passive: 'Builds solidarity and keeps people moving when corridors close.',
    burnoutMax: 10,
    actionsPerTurn: { CORE: 2, FULL: 3 },
    actionIds: ['rest_and_care', 'cultural_resonance', 'mutual_aid_network', 'community_mobilization', 'safe_passage'],
    breakthroughActionIds: ['mass_mobilization'],
  },
  {
    id: 'investigative_journalist',
    name: 'Investigative Journalist',
    shortName: 'Journalist',
    passive: 'Turns testimony into evidence and cracks open truth windows.',
    burnoutMax: 9,
    actionsPerTurn: { CORE: 2, FULL: 3 },
    actionIds: ['rest_and_care', 'cultural_resonance', 'field_investigation', 'counter_disinfo', 'truth_window'],
    breakthroughActionIds: ['global_expose'],
  },
  {
    id: 'human_rights_lawyer',
    name: 'Human Rights Lawyer',
    shortName: 'Lawyer',
    passive: 'Clears locks, raises remedy pressure, and protects civic remedies.',
    burnoutMax: 10,
    actionsPerTurn: { CORE: 2, FULL: 3 },
    actionIds: ['rest_and_care', 'cultural_resonance', 'emergency_injunction', 'clear_aid_corridor', 'remedy_dossier'],
    breakthroughActionIds: ['international_tribunal'],
  },
  {
    id: 'climate_energy_planner',
    name: 'Climate & Energy Planner',
    shortName: 'Planner',
    passive: 'Builds resilient infrastructure that slows climate spillover.',
    burnoutMax: 10,
    actionsPerTurn: { CORE: 2, FULL: 3 },
    actionIds: ['rest_and_care', 'cultural_resonance', 'build_microgrid', 'disaster_preparedness', 'resilience_retrofit'],
    breakthroughActionIds: ['rapid_decarbonization'],
  },
];

const charter: CharterClauseDefinition[] = [
  {
    id: 'protected_humanitarian_corridors',
    title: 'Protected Humanitarian Corridors',
    description: 'Civilian access routes stay open despite escalation.',
    prerequisites: [
      { kind: 'compare', left: { type: 'front_stat', front: 'WAR', stat: 'pressure' }, op: '<=', right: 6 },
      { kind: 'compare', left: { type: 'front_stat', front: 'RIGHTS', stat: 'protection' }, op: '>=', right: 5 },
    ],
    ratifyEffects: [
      { type: 'remove_lock', region: 'MENA', lock: 'AidAccess' },
      { type: 'modify_front_stat', front: 'RIGHTS', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'right_to_information',
    title: 'Right To Information',
    description: 'Independent reporting and public truth claims are protected.',
    prerequisites: [
      { kind: 'compare', left: { type: 'resource', resource: 'evidence' }, op: '>=', right: 5 },
      { kind: 'compare', left: { type: 'front_stat', front: 'SPEECH_INFO', stat: 'protection' }, op: '>=', right: 5 },
    ],
    ratifyEffects: [
      { type: 'remove_lock', region: 'ANY', lock: 'Censorship' },
      { type: 'modify_front_stat', front: 'SPEECH_INFO', stat: 'pressure', delta: -1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'right_to_remedy',
    title: 'Right To Remedy',
    description: 'Access to remedy becomes enforceable across targeted regions.',
    prerequisites: [
      { kind: 'compare', left: { type: 'front_stat', front: 'RIGHTS', stat: 'protection' }, op: '>=', right: 6 },
      { kind: 'compare', left: { type: 'flag', scope: 'scenario', key: 'charter_progress_total' }, op: '>=', right: 2 },
    ],
    ratifyEffects: [{ type: 'modify_front_stat', front: 'RIGHTS', stat: 'impact', delta: -1, clamp: { min: 0, max: 10 } }],
  },
  {
    id: 'climate_reparations_compact',
    title: 'Climate Reparations Compact',
    description: 'Resources move toward those living inside the crisis first.',
    prerequisites: [
      { kind: 'compare', left: { type: 'front_stat', front: 'CLIMATE', stat: 'impact' }, op: '<=', right: 4 },
      { kind: 'compare', left: { type: 'resource', resource: 'capacity' }, op: '>=', right: 3 },
    ],
    ratifyEffects: [
      { type: 'gain_resource', resource: 'capacity', amount: 2 },
      { type: 'modify_front_stat', front: 'POVERTY', stat: 'pressure', delta: -1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'energy_commons',
    title: 'Energy Commons',
    description: 'Local resilience infrastructure is treated as shared rights work.',
    prerequisites: [
      { kind: 'compare', left: { type: 'front_stat', front: 'ENERGY', stat: 'protection' }, op: '>=', right: 6 },
      { kind: 'compare', left: { type: 'resource', resource: 'capacity' }, op: '>=', right: 2 },
    ],
    ratifyEffects: [
      { type: 'modify_front_stat', front: 'ENERGY', stat: 'pressure', delta: -1, clamp: { min: 0, max: 10 } },
      { type: 'gain_resource', resource: 'capacity', amount: 1 },
    ],
  },
  {
    id: 'cultural_survival_covenant',
    title: 'Cultural Survival Covenant',
    description: 'Culture is defended as a material right, not a luxury.',
    prerequisites: [
      { kind: 'compare', left: { type: 'front_stat', front: 'CULTURE', stat: 'protection' }, op: '>=', right: 6 },
      { kind: 'compare', left: { type: 'resource', resource: 'solidarity' }, op: '>=', right: 4 },
    ],
    ratifyEffects: [
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'impact', delta: -1, clamp: { min: 0, max: 10 } },
      { type: 'gain_resource', resource: 'solidarity', amount: 2 },
    ],
  },
];

const hooks: RuleDefinition[] = [
  {
    id: 'deterioration_aid_access',
    hook: 'on_world_phase_pre',
    when: { kind: 'hasLock', region: 'ANY', lock: 'AidAccess' },
    emoji: '🛡️',
    message: 'Aid corridors remain obstructed.',
    effects: [{ type: 'modify_front_stat', front: 'RIGHTS', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } }],
  },
  {
    id: 'deterioration_censorship',
    hook: 'on_world_phase_pre',
    when: { kind: 'hasLock', region: 'ANY', lock: 'Censorship' },
    emoji: '📣',
    message: 'Censorship narrows what can be said publicly.',
    effects: [{ type: 'modify_front_stat', front: 'SPEECH_INFO', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } }],
  },
  {
    id: 'deterioration_surveillance',
    hook: 'on_world_phase_pre',
    when: { kind: 'hasLock', region: 'ANY', lock: 'Surveillance' },
    emoji: '⚖️',
    message: 'Surveillance deepens rights pressure.',
    effects: [{ type: 'modify_front_stat', front: 'RIGHTS', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } }],
  },
  {
    id: 'coupling_poverty_disinfo',
    hook: 'on_end_phase',
    when: { kind: 'compare', left: { type: 'front_stat', front: 'POVERTY', stat: 'pressure' }, op: '>=', right: 7 },
    emoji: '🛰️',
    message: 'Poverty pressure amplifies disinformation.',
    effects: [
      { type: 'add_token', region: 'MENA', token: 'disinfo', count: 1 },
      { type: 'add_token', region: 'SoutheastAsia', token: 'disinfo', count: 1 },
      { type: 'add_token', region: 'LatinAmerica', token: 'disinfo', count: 1 },
    ],
  },
  {
    id: 'coupling_war_displacement',
    hook: 'on_end_phase',
    when: { kind: 'compare', left: { type: 'front_stat', front: 'WAR', stat: 'pressure' }, op: '>=', right: 7 },
    emoji: '🕊️',
    message: 'War pressure drives new displacement and rights harm.',
    effects: [
      { type: 'add_token', region: 'MENA', token: 'displacement', count: 1 },
      { type: 'modify_front_stat', front: 'RIGHTS', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'coupling_war_threat',
    hook: 'on_end_phase',
    when: { kind: 'compare', left: { type: 'front_stat', front: 'WAR', stat: 'pressure' }, op: '>=', right: 8 },
    emoji: '❌',
    message: 'War pressure threatens local institutions in MENA.',
    effects: [{ type: 'damage_institution', region: 'MENA' }],
  },
];

const captureCards: CardDefinition[] = [
  {
    id: 'capture_extraction_licensing',
    deck: 'capture',
    name: 'Extraction Licensing',
    text: 'Contracts arrive before consent does.',
    mode: 'BOTH',
    tags: ['EXTRACTION'],
    emoji: '⛏️',
    pillar: 'EXTRACTION',
    effects: [
      { type: 'modify_front_stat', front: 'ENERGY', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'POVERTY', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'capture_debt_discipline',
    deck: 'capture',
    name: 'Debt Discipline',
    text: 'Austerity arrives wrapped in expert language.',
    mode: 'BOTH',
    tags: ['EXTRACTION'],
    emoji: '💳',
    pillar: 'EXTRACTION',
    effects: [
      { type: 'modify_front_stat', front: 'POVERTY', stat: 'pressure', delta: 2, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'RIGHTS', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'capture_aid_conditionality',
    deck: 'capture',
    name: 'Aid Conditionality',
    text: 'Relief becomes leverage.',
    mode: 'BOTH',
    tags: ['EXTRACTION'],
    emoji: '📦',
    pillar: 'EXTRACTION',
    effects: [
      { type: 'add_lock', region: 'MENA', lock: 'AidAccess' },
      {
        type: 'choice',
        choiceType: 'compromise',
        prompt: 'Take conditioned relief now, or refuse and absorb the pressure.',
        options: [
          {
            id: 'accept_conditioned_relief',
            label: 'Accept conditioned relief',
            description: 'Gain relief now, take debt later.',
            effects: [
              { type: 'gain_resource', resource: 'relief', amount: 2 },
              { type: 'add_token', region: 'ANY', token: 'compromise_debt', count: 1 },
              {
                type: 'delayed_effect',
                afterRounds: 2,
                description: 'Conditioned relief returns as delayed rights harm.',
                effects: [
                  { type: 'modify_front_stat', front: 'RIGHTS', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
                  { type: 'modify_front_stat', front: 'POVERTY', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
                ],
              },
            ],
          },
          {
            id: 'reject_conditioned_relief',
            label: 'Reject the deal',
            description: 'Hold the line and keep the debt out.',
            effects: [{ type: 'modify_front_stat', front: 'RIGHTS', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } }],
          },
        ],
      },
    ],
  },
  {
    id: 'capture_pipeline_security',
    deck: 'capture',
    name: 'Pipeline Security',
    text: 'Resource corridors are militarized in the name of stability.',
    mode: 'BOTH',
    tags: ['MILITARIZATION'],
    emoji: '🛢️',
    pillar: 'MILITARIZATION',
    effects: [
      { type: 'modify_front_stat', front: 'WAR', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'ENERGY', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'capture_border_industry',
    deck: 'capture',
    name: 'Border Industry',
    text: 'Displacement becomes someone else’s quarterly forecast.',
    mode: 'BOTH',
    tags: ['MILITARIZATION'],
    emoji: '🚧',
    pillar: 'MILITARIZATION',
    effects: [
      { type: 'add_token', region: 'MENA', token: 'displacement', count: 1 },
      { type: 'modify_front_stat', front: 'WAR', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'capture_counterinsurgency_grant',
    deck: 'capture',
    name: 'Counterinsurgency Grant',
    text: 'Security aid arrives faster than medicine.',
    mode: 'BOTH',
    tags: ['MILITARIZATION'],
    emoji: '🎖️',
    pillar: 'MILITARIZATION',
    effects: [
      { type: 'add_lock', region: 'MENA', lock: 'Surveillance' },
      { type: 'modify_front_stat', front: 'RIGHTS', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'capture_emergency_law',
    deck: 'capture',
    name: 'Emergency Law',
    text: 'Temporary powers become a long-term habit.',
    mode: 'BOTH',
    tags: ['CONTROL'],
    emoji: '📜',
    pillar: 'CONTROL',
    effects: [
      { type: 'modify_track', target: { type: 'civic_space_index' }, delta: 1, clamp: { min: 0, max: 4 } },
      { type: 'add_lock', region: 'MENA', lock: 'Censorship' },
    ],
  },
  {
    id: 'capture_judicial_capture',
    deck: 'capture',
    name: 'Judicial Capture',
    text: 'Law is repurposed as a narrow gate.',
    mode: 'BOTH',
    tags: ['CONTROL'],
    emoji: '⚖️',
    pillar: 'CONTROL',
    effects: [
      { type: 'modify_front_stat', front: 'RIGHTS', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'add_lock', region: 'NorthAmerica', lock: 'Surveillance' },
    ],
  },
  {
    id: 'capture_data_fusion',
    deck: 'capture',
    name: 'Data Fusion',
    text: 'Every register becomes a watchlist when the system decides it should.',
    mode: 'BOTH',
    tags: ['CONTROL'],
    emoji: '🛰️',
    pillar: 'CONTROL',
    effects: [
      { type: 'add_lock', region: 'Europe', lock: 'Surveillance' },
      { type: 'add_lock', region: 'MENA', lock: 'Surveillance' },
    ],
  },
  {
    id: 'capture_platform_amplification',
    deck: 'capture',
    name: 'Platform Amplification',
    text: 'Division converts neatly into engagement.',
    mode: 'BOTH',
    tags: ['MANUFACTURED_CONSENT'],
    emoji: '📣',
    pillar: 'MANUFACTURED_CONSENT',
    effects: [
      { type: 'modify_front_stat', front: 'SPEECH_INFO', stat: 'pressure', delta: 2, clamp: { min: 0, max: 10 } },
      { type: 'add_token', region: 'MENA', token: 'disinfo', count: 1 },
      { type: 'add_token', region: 'LatinAmerica', token: 'disinfo', count: 1 },
    ],
  },
  {
    id: 'capture_culture_wash',
    deck: 'capture',
    name: 'Culture Wash',
    text: 'The sponsors fund the mural and silence the people it was meant for.',
    mode: 'BOTH',
    tags: ['MANUFACTURED_CONSENT'],
    emoji: '🎭',
    pillar: 'MANUFACTURED_CONSENT',
    effects: [
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'add_token', region: 'SoutheastAsia', token: 'disinfo', count: 1 },
    ],
  },
  {
    id: 'capture_spotlight_summit',
    deck: 'capture',
    name: 'Spotlight Summit',
    text: 'A performative summit promises reform while narrowing actual civic space.',
    mode: 'FULL',
    tags: ['MANUFACTURED_CONSENT', 'SPOTLIGHT'],
    emoji: '🎤',
    pillar: 'MANUFACTURED_CONSENT',
    effects: [
      { type: 'modify_track', target: { type: 'civic_space_index' }, delta: 1, clamp: { min: 0, max: 4 } },
      { type: 'modify_front_stat', front: 'SPEECH_INFO', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'capture_spotlight_peacemaker',
    deck: 'capture',
    name: 'Spotlight Peacemaker',
    text: 'An archetype steps in to manage optics, not harm.',
    mode: 'FULL',
    tags: ['MILITARIZATION', 'SPOTLIGHT'],
    emoji: '🕴️',
    pillar: 'MILITARIZATION',
    effects: [
      { type: 'modify_front_stat', front: 'WAR', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'RIGHTS', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
];

const crisisCards: CardDefinition[] = [
  {
    id: 'crisis_unprecedented_heatwave',
    deck: 'crisis',
    name: 'Unprecedented Heatwave',
    text: 'What used to be exceptional becomes seasonal.',
    mode: 'BOTH',
    tags: ['CLIMATE'],
    emoji: '🔥',
    effects: [
      { type: 'modify_track', target: { type: 'temperature' }, delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'CLIMATE', stat: 'impact', delta: 2, clamp: { min: 0, max: 10 } },
      { type: 'add_token', region: 'SouthAsia', token: 'displacement', count: 1 },
    ],
  },
  {
    id: 'crisis_cyclone_landfall',
    deck: 'crisis',
    name: 'Cyclone Landfall',
    text: 'Winds erase what the budget never repaired.',
    mode: 'BOTH',
    tags: ['CLIMATE'],
    emoji: '🌪️',
    effects: [
      { type: 'modify_front_stat', front: 'CLIMATE', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'add_token', region: 'PacificIslands', token: 'displacement', count: 1 },
    ],
  },
  {
    id: 'crisis_grid_sabotage',
    deck: 'crisis',
    name: 'Grid Sabotage',
    text: 'Energy insecurity becomes a deliberate tactic.',
    mode: 'BOTH',
    tags: ['ENERGY'],
    emoji: '⚡',
    effects: [{ type: 'modify_front_stat', front: 'ENERGY', stat: 'impact', delta: 2, clamp: { min: 0, max: 10 } }],
  },
  {
    id: 'crisis_blackout',
    deck: 'crisis',
    name: 'Forced Blackout',
    text: 'Darkness is used to fragment care and witness.',
    mode: 'BOTH',
    tags: ['ENERGY', 'WAR'],
    emoji: '🌑',
    effects: [
      { type: 'modify_front_stat', front: 'ENERGY', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'add_lock', region: 'MENA', lock: 'AidAccess' },
    ],
  },
  {
    id: 'crisis_border_closure',
    deck: 'crisis',
    name: 'Border Closure',
    text: 'The route stays open for weapons and closed for care.',
    mode: 'BOTH',
    tags: ['WAR'],
    emoji: '🚷',
    effects: [
      { type: 'add_lock', region: 'MENA', lock: 'AidAccess' },
      { type: 'modify_front_stat', front: 'WAR', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'crisis_hospital_siege',
    deck: 'crisis',
    name: 'Hospital Siege',
    text: 'Civilian care is treated as a liability.',
    mode: 'BOTH',
    tags: ['WAR', 'RIGHTS'],
    emoji: '🏥',
    effects: [
      { type: 'modify_front_stat', front: 'RIGHTS', stat: 'impact', delta: 2, clamp: { min: 0, max: 10 } },
      { type: 'add_token', region: 'MENA', token: 'displacement', count: 1 },
    ],
  },
  {
    id: 'crisis_archive_burning',
    deck: 'crisis',
    name: 'Archive Burning',
    text: 'Memory itself is treated as contraband.',
    mode: 'BOTH',
    tags: ['CULTURE', 'SPEECH_INFO'],
    emoji: '🗃️',
    effects: [
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'SPEECH_INFO', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'crisis_speech_crackdown',
    deck: 'crisis',
    name: 'Speech Crackdown',
    text: 'Dissent is reclassified as disorder.',
    mode: 'BOTH',
    tags: ['SPEECH_INFO'],
    emoji: '🔇',
    effects: [
      { type: 'add_lock', region: 'SoutheastAsia', lock: 'Censorship' },
      { type: 'modify_front_stat', front: 'SPEECH_INFO', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'crisis_price_spike',
    deck: 'crisis',
    name: 'Price Spike',
    text: 'Household survival is made to carry macroeconomic shocks.',
    mode: 'BOTH',
    tags: ['POVERTY'],
    emoji: '📈',
    effects: [{ type: 'modify_front_stat', front: 'POVERTY', stat: 'impact', delta: 2, clamp: { min: 0, max: 10 } }],
  },
  {
    id: 'crisis_displacement_wave',
    deck: 'crisis',
    name: 'Displacement Wave',
    text: 'Families move because staying becomes impossible.',
    mode: 'BOTH',
    tags: ['WAR', 'CLIMATE'],
    emoji: '🧍',
    effects: [
      { type: 'add_token', region: 'MENA', token: 'displacement', count: 1 },
      { type: 'add_token', region: 'PacificIslands', token: 'displacement', count: 1 },
    ],
  },
  {
    id: 'crisis_flooded_streets',
    deck: 'crisis',
    name: 'Flooded Streets',
    text: 'Planning documents float where roads used to be.',
    mode: 'BOTH',
    tags: ['CLIMATE'],
    emoji: '🌊',
    effects: [
      { type: 'modify_front_stat', front: 'CLIMATE', stat: 'impact', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'modify_front_stat', front: 'POVERTY', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'crisis_artists_detained',
    deck: 'crisis',
    name: 'Artists Detained',
    text: 'The state understands art as coordination and treats it accordingly.',
    mode: 'BOTH',
    tags: ['CULTURE', 'CONTROL'],
    emoji: '🎨',
    effects: [
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'pressure', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'add_lock', region: 'LatinAmerica', lock: 'Censorship' },
    ],
  },
];

const cultureCards: CardDefinition[] = [
  {
    id: 'culture_underground_festival',
    deck: 'culture',
    name: 'Underground Festival',
    text: 'A gathering survives the curfew and keeps memory audible.',
    mode: 'BOTH',
    tags: ['MORALE', 'TRUTH'],
    emoji: '🎭',
    effects: [
      { type: 'modify_track', target: { type: 'player_burnout', player: 'acting_player' }, delta: -2 },
      { type: 'set_flag', scope: 'round', key: 'truth_window:target_region', value: true },
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'culture_street_kitchen',
    deck: 'culture',
    name: 'Street Kitchen',
    text: 'Care work becomes a visible refusal of isolation.',
    mode: 'BOTH',
    tags: ['MORALE', 'RESOURCE'],
    emoji: '🥘',
    effects: [
      { type: 'gain_resource', resource: 'solidarity', amount: 2 },
      { type: 'modify_track', target: { type: 'player_burnout', player: 'acting_player' }, delta: -1 },
    ],
  },
  {
    id: 'culture_poetry_circle',
    deck: 'culture',
    name: 'Poetry Circle',
    text: 'Words travel where formal speech no longer can.',
    mode: 'BOTH',
    tags: ['TRUTH'],
    emoji: '📚',
    effects: [
      { type: 'gain_resource', resource: 'evidence', amount: 1 },
      { type: 'set_flag', scope: 'round', key: 'truth_window:target_region', value: true },
    ],
  },
  {
    id: 'culture_radio_theatre',
    deck: 'culture',
    name: 'Radio Theatre',
    text: 'A story slips through a channel the censors forgot to close.',
    mode: 'BOTH',
    tags: ['TRUTH', 'RESOURCE'],
    emoji: '📻',
    effects: [
      { type: 'remove_lock', region: 'target_region', lock: 'Censorship' },
      { type: 'gain_resource', resource: 'solidarity', amount: 1 },
    ],
  },
  {
    id: 'culture_mutual_songbook',
    deck: 'culture',
    name: 'Mutual Songbook',
    text: 'A chorus keeps people moving together under pressure.',
    mode: 'BOTH',
    tags: ['MORALE', 'RESOURCE'],
    emoji: '🎶',
    effects: [
      { type: 'gain_resource', resource: 'capacity', amount: 1 },
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'culture_memory_workshop',
    deck: 'culture',
    name: 'Memory Workshop',
    text: 'People document what power hopes will disappear.',
    mode: 'BOTH',
    tags: ['RIGHTS', 'TRUTH'],
    emoji: '🧵',
    effects: [
      { type: 'gain_resource', resource: 'evidence', amount: 1 },
      { type: 'modify_front_stat', front: 'RIGHTS', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
    ],
  },
  {
    id: 'culture_rooftop_concert',
    deck: 'culture',
    name: 'Rooftop Concert',
    text: 'The sound carries farther than the checkpoints expected.',
    mode: 'BOTH',
    tags: ['MORALE', 'RIGHTS'],
    emoji: '🎺',
    effects: [
      { type: 'modify_track', target: { type: 'player_burnout', player: 'acting_player' }, delta: -1 },
      { type: 'modify_front_stat', front: 'CULTURE', stat: 'protection', delta: 1, clamp: { min: 0, max: 10 } },
      { type: 'remove_token', region: 'target_region', token: 'disinfo', count: 1 },
    ],
  },
  {
    id: 'culture_story_brigade',
    deck: 'culture',
    name: 'Story Brigade',
    text: 'Collective storytelling becomes a logistics network in disguise.',
    mode: 'BOTH',
    tags: ['RESOURCE', 'TRUTH'],
    emoji: '📝',
    effects: [
      { type: 'gain_resource', resource: 'solidarity', amount: 1 },
      { type: 'gain_resource', resource: 'capacity', amount: 1 },
      { type: 'set_flag', scope: 'round', key: 'truth_window:target_region', value: true },
    ],
  },
];

const pack: PackDefinition = {
  id: 'base',
  type: 'base',
  version: '1.0.0',
  fronts,
  regions,
  institutions,
  roles,
  actions,
  charter,
  cards: [...captureCards, ...crisisCards, ...cultureCards],
  hooks,
};

export default pack;
