import type { ResistanceCardDefinition } from '../../../engine/adapters/compat/types.ts';

export const resistanceCards: ResistanceCardDefinition[] = [
  {
    id: 'res_alg_urban_cell_network',
    deck: 'resistance',
    type: 'action',
    name: 'Urban Cell Network',
    text: 'Acting faction gains 1 Evidence and adds 1 Comrade to the target region.',
    effects: [
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
      { type: 'add_comrades', region: 'target_region', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_alg_mountain_guerrilla_offensive',
    deck: 'resistance',
    type: 'support',
    name: 'Mountain Guerrilla Offensive',
    text: 'Acting faction gets +2 on a campaign launched in Kabylie Mountains.',
    campaignBonus: 2,
    regionBonus: 'KabylieMountains',
  },
  {
    id: 'res_alg_international_student_solidarity',
    deck: 'resistance',
    type: 'action',
    name: 'International Student Solidarity',
    text: 'Acting faction raises Global Gaze by 2 and gains 1 Evidence.',
    effects: [
      { type: 'modify_gaze', delta: 2 },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_alg_labor_strike',
    deck: 'resistance',
    type: 'action',
    name: 'Labor Strike',
    text: 'Advance Empty Stomach by 1 and add 1 Comrade to Oran for the acting faction.',
    effects: [
      { type: 'modify_domain', domain: 'EmptyStomach', delta: 1 },
      { type: 'add_comrades', region: 'Oran', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_alg_cultural_resistance_campaign',
    deck: 'resistance',
    type: 'support',
    name: 'Cultural Resistance Campaign',
    text: 'Acting faction gets +1 on a Silenced Truth campaign.',
    campaignBonus: 1,
    domainBonus: 'SilencedTruth',
  },
  {
    id: 'res_alg_underground_printing_press',
    deck: 'resistance',
    type: 'action',
    name: 'Underground Printing Press',
    text: 'Acting faction gains 2 Evidence and raises Global Gaze by 1.',
    effects: [
      { type: 'gain_evidence', seat: 'acting_player', amount: 2 },
      { type: 'modify_gaze', delta: 1 },
    ],
  },
  {
    id: 'res_alg_mass_funeral_mobilization',
    deck: 'resistance',
    type: 'action',
    name: 'Mass Funeral Mobilization',
    text: 'Add 2 Comrades to Algiers for the acting faction and advance Revolutionary Wave by 1.',
    effects: [
      { type: 'add_comrades', region: 'Algiers', seat: 'acting_player', amount: 2 },
      { type: 'modify_domain', domain: 'RevolutionaryWave', delta: 1 },
    ],
  },
  {
    id: 'res_alg_negotiation_delegation',
    deck: 'resistance',
    type: 'action',
    name: 'Negotiation Delegation',
    text: 'Acting faction raises Global Gaze by 1 and gains 1 Evidence.',
    effects: [
      { type: 'modify_gaze', delta: 1 },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_alg_cross_border_supply',
    deck: 'resistance',
    type: 'action',
    name: 'Cross-Border Supply',
    text: 'Add 2 Comrades to Tunisian Border for the acting faction and gain 1 Evidence.',
    effects: [
      { type: 'add_comrades', region: 'TunisianBorder', seat: 'acting_player', amount: 2 },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_alg_prison_solidarity_network',
    deck: 'resistance',
    type: 'action',
    name: 'Prison Solidarity Network',
    text: 'Reduce Gilded Cage by 1 and give the acting faction 1 Evidence.',
    effects: [
      { type: 'modify_domain', domain: 'GildedCage', delta: -1 },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_alg_ceasefire_proposal',
    deck: 'resistance',
    type: 'support',
    name: 'Ceasefire Proposal',
    text: 'Acting faction gets +1 on an Unfinished Justice campaign.',
    campaignBonus: 1,
    domainBonus: 'UnfinishedJustice',
  },
  {
    id: 'res_alg_grassroots_education',
    deck: 'resistance',
    type: 'action',
    name: 'Grassroots Education',
    text: 'Advance Revolutionary Wave by 1 and give the acting faction 1 Evidence.',
    effects: [
      { type: 'modify_domain', domain: 'RevolutionaryWave', delta: 1 },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
];
