import type { ResistanceCardDefinition } from '../../../engine/adapters/compat/types.ts';

export const resistanceCards: ResistanceCardDefinition[] = [
  {
    id: 'res_corr_egyptian_medic_convoy',
    deck: 'resistance',
    type: 'action',
    name: 'Egyptian Medic Convoy',
    text: 'A hard-won convoy clears one narrow opening. Move witness, medicine, and pressure before the gate closes again.',
    effects: [
      { type: 'modify_custom_track', trackId: 'egypt_corridor', delta: 1, clamp: { min: 0, max: 6 } },
      { type: 'remove_extraction', region: 'GazaWestBank', amount: 1 },
    ],
  },
  {
    id: 'res_corr_qatari_mediation_channel',
    deck: 'resistance',
    type: 'action',
    name: 'Qatari Mediation Channel',
    text: 'Negotiation space opens just long enough to move names, bodies, and demands.',
    effects: [
      { type: 'modify_custom_track', trackId: 'qatar_corridor', delta: 1, clamp: { min: 0, max: 6 } },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_corr_turkish_port_delay',
    deck: 'resistance',
    type: 'action',
    name: 'Turkish Port Delay',
    text: 'Logistics slow, paperwork piles up, and another military timetable slips.',
    effects: [
      { type: 'modify_custom_track', trackId: 'turkey_corridor', delta: 1, clamp: { min: 0, max: 6 } },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_corr_jordanian_hospital_witness',
    deck: 'resistance',
    type: 'action',
    name: 'Jordanian Hospital Witness',
    text: 'Medical testimony crosses a brittle border and forces the war back into public view.',
    effects: [
      { type: 'modify_custom_track', trackId: 'jordan_corridor', delta: 1, clamp: { min: 0, max: 6 } },
      { type: 'modify_gaze', delta: 1 },
    ],
  },
  {
    id: 'res_corr_venezuelan_communal_kitchens',
    deck: 'resistance',
    type: 'action',
    name: 'Venezuelan Communal Kitchens',
    text: 'The commune keeps people alive, and survival itself becomes a political refusal.',
    effects: [
      { type: 'add_comrades', region: 'CaribbeanSiege', seat: 'acting_player', amount: 4 },
      { type: 'modify_domain', domain: 'EmptyStomach', delta: 1 },
    ],
  },
  {
    id: 'res_corr_cuban_radio_brigade',
    deck: 'resistance',
    type: 'action',
    name: 'Cuban Radio Brigade',
    text: 'Memory and signal travel together. The blockade line is breached by persistence, not permission.',
    effects: [
      { type: 'gain_evidence', seat: 'acting_player', amount: 2 },
      { type: 'modify_domain', domain: 'StolenVoice', delta: 1 },
    ],
  },
  {
    id: 'res_corr_street_to_strait_coordination',
    deck: 'resistance',
    type: 'action',
    name: 'Street-to-Strait Coordination',
    text: 'Dockworkers, medics, communes, and witness networks synchronize one brief counter-current.',
    effects: [
      { type: 'modify_custom_track', trackId: 'saudi_posture', delta: 1, clamp: { min: 0, max: 2 } },
      { type: 'modify_custom_track', trackId: 'uae_posture', delta: 1, clamp: { min: 0, max: 2 } },
      { type: 'draw_resistance', seat: 'acting_player', count: 1 },
    ],
  },
  {
    id: 'sup_corr_spain_breaks_ranks',
    deck: 'resistance',
    type: 'support',
    name: 'Spain Breaks Ranks',
    text: 'Public refusal from Madrid opens anti-war space and weakens the claim that escalation speaks for all of Europe.',
    campaignBonus: 2,
    domainBonus: 'WarMachine',
  },
  {
    id: 'sup_corr_gaza_archive_stream',
    deck: 'resistance',
    type: 'support',
    name: 'Gaza Archive Stream',
    text: 'Phones, lists, names, and moving testimony hold the line against planned disappearance.',
    campaignBonus: 2,
    domainBonus: 'SilencedTruth',
  },
  {
    id: 'sup_corr_prisoner_letter_chain',
    deck: 'resistance',
    type: 'support',
    name: 'Prisoner Letter Chain',
    text: 'Detention routes become testimony routes and the carceral line starts to fray.',
    campaignBonus: 2,
    domainBonus: 'GildedCage',
  },
  {
    id: 'sup_corr_red_sea_dock_strike',
    deck: 'resistance',
    type: 'support',
    name: 'Red Sea Dock Strike',
    text: 'Port labor turns logistics into leverage and forces shipping power to feel delay as cost.',
    campaignBonus: 2,
    domainBonus: 'FossilGrip',
  },
  {
    id: 'sup_corr_black_sea_grain_solidarity',
    deck: 'resistance',
    type: 'support',
    name: 'Black Sea Grain Solidarity',
    text: 'Grain, convoy information, and food politics are reclaimed from war planners and insurers.',
    campaignBonus: 2,
    domainBonus: 'EmptyStomach',
  },
  {
    id: 'sup_corr_cuban_memory_brigade',
    deck: 'resistance',
    type: 'support',
    name: 'Cuban Memory Brigade',
    text: 'Songs, schools, and neighborhood recall make erasure expensive and unfinished.',
    campaignBonus: 2,
    domainBonus: 'StolenVoice',
  },
  {
    id: 'sup_corr_communal_defense_assembly',
    deck: 'resistance',
    type: 'support',
    name: 'Communal Defense Assembly',
    text: 'The coalition regains coherence through assembly, discipline, and shared sacrifice.',
    campaignBonus: 2,
    domainBonus: 'RevolutionaryWave',
  },
];

export default resistanceCards;
