import type { ResistanceCardDefinition } from '../../../engine/adapters/compat/types.ts';

export const resistanceCards: ResistanceCardDefinition[] = [
  {
    id: 'res_corr_egyptian_medic_convoy',
    deck: 'resistance',
    type: 'action',
    name: 'Egyptian Medic Convoy',
    text: 'A narrow convoy window gets wounded people, medicine, and witness lists through before the gate is sealed again.',
    effects: [
      { type: 'modify_custom_track', trackId: 'egypt_corridor', delta: 1, clamp: { min: 0, max: 6 } },
      { type: 'remove_extraction', region: 'GazaWestBank', amount: 1 },
    ],
  },
  {
    id: 'res_corr_qatari_mediation_channel',
    deck: 'resistance',
    type: 'action',
    name: 'Qatari Mediation Channel',
    text: 'A mediation pause moves detainee names, casualty lists, and negotiation demands before the bombing cycle resumes.',
    effects: [
      { type: 'modify_custom_track', trackId: 'qatar_corridor', delta: 1, clamp: { min: 0, max: 6 } },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_corr_turkish_port_delay',
    deck: 'resistance',
    type: 'action',
    name: 'Turkish Port Delay',
    text: 'Customs friction and port delay slow military cargo long enough to document routes and buy time.',
    effects: [
      { type: 'modify_custom_track', trackId: 'turkey_corridor', delta: 1, clamp: { min: 0, max: 6 } },
      { type: 'gain_evidence', seat: 'acting_player', amount: 1 },
    ],
  },
  {
    id: 'res_corr_jordanian_hospital_witness',
    deck: 'resistance',
    type: 'action',
    name: 'Jordanian Hospital Witness',
    text: 'Wounded evacuees and hospital records cross the border, forcing massacre evidence back into public view.',
    effects: [
      { type: 'modify_custom_track', trackId: 'jordan_corridor', delta: 1, clamp: { min: 0, max: 6 } },
      { type: 'modify_gaze', delta: 1 },
    ],
  },
  {
    id: 'res_corr_venezuelan_communal_kitchens',
    deck: 'resistance',
    type: 'action',
    name: 'Venezuelan Communal Kitchens',
    text: 'Communal kitchens blunt sanctions hunger and keep neighborhoods politically present.',
    effects: [
      { type: 'add_comrades', region: 'CaribbeanSiege', seat: 'acting_player', amount: 4 },
      { type: 'modify_domain', domain: 'EmptyStomach', delta: 1 },
    ],
  },
  {
    id: 'res_corr_cuban_radio_brigade',
    deck: 'resistance',
    type: 'action',
    name: 'Cuban Radio Brigade',
    text: 'Neighborhood radio carries memory, alerts, and anti-blockade coordination when platforms and banks choke movement.',
    effects: [
      { type: 'gain_evidence', seat: 'acting_player', amount: 2 },
      { type: 'modify_domain', domain: 'SilencedTruth', delta: 1 },
    ],
  },
  {
    id: 'res_corr_street_to_strait_coordination',
    deck: 'resistance',
    type: 'action',
    name: 'Street-to-Strait Coordination',
    text: 'Dockworkers, medics, communes, and witness networks line up one brief corridor that delays war logistics and opens organizing space.',
    effects: [
      { type: 'modify_custom_track', trackId: 'saudi_posture', delta: 1, clamp: { min: 0, max: 2 } },
      { type: 'modify_custom_track', trackId: 'uae_posture', delta: 1, clamp: { min: 0, max: 2 } },
      { type: 'draw_resistance', seat: 'acting_player', count: 1 },
    ],
  },
  {
    id: 'sup_corr_spain_breaks_ranks',
    deck: 'resistance',
    type: 'support',
    name: 'Spain Breaks Ranks',
    text: 'Acting faction gets +2 on a War Machine campaign. Madrid\'s public refusal punctures Atlantic unanimity and gives anti-war organizers usable political cover.',
    campaignBonus: 2,
    domainBonus: 'WarMachine',
  },
  {
    id: 'sup_corr_gaza_archive_stream',
    deck: 'resistance',
    type: 'support',
    name: 'Gaza Archive Stream',
    text: 'Acting faction gets +2 on a Witness Corridors campaign. Phones, martyr lists, clinic logs, and burial records keep evidence moving against erasure.',
    campaignBonus: 2,
    domainBonus: 'SilencedTruth',
  },
  {
    id: 'sup_corr_prisoner_letter_chain',
    deck: 'resistance',
    type: 'support',
    name: 'Prisoner Letter Chain',
    text: 'Acting faction gets +2 on a Sanctions Breach campaign. Letters from prison turn disappearance into public testimony and weaken the state\'s monopoly on narrative.',
    campaignBonus: 2,
    domainBonus: 'GildedCage',
  },
  {
    id: 'sup_corr_red_sea_dock_strike',
    deck: 'resistance',
    type: 'support',
    name: 'Red Sea Dock Strike',
    text: 'Acting faction gets +2 on a Chokepoint Breakage campaign. A port stoppage turns delay into cost for shippers, insurers, and war logistics.',
    campaignBonus: 2,
    domainBonus: 'FossilGrip',
  },
  {
    id: 'sup_corr_black_sea_grain_solidarity',
    deck: 'resistance',
    type: 'support',
    name: 'Black Sea Grain Solidarity',
    text: 'Acting faction gets +2 on a Bread Under Siege campaign. Grain routes and convoy information are reclaimed for food survival instead of war planning.',
    campaignBonus: 2,
    domainBonus: 'EmptyStomach',
  },
  {
    id: 'sup_corr_cuban_memory_brigade',
    deck: 'resistance',
    type: 'support',
    name: 'Cuban Memory Brigade',
    text: 'Acting faction gets +2 on a Witness Corridors campaign. Songs, classrooms, and neighborhood memory keep blockade trauma politically legible and hard to erase.',
    campaignBonus: 2,
    domainBonus: 'SilencedTruth',
  },
  {
    id: 'sup_corr_communal_defense_assembly',
    deck: 'resistance',
    type: 'support',
    name: 'Communal Defense Assembly',
    text: 'Acting faction gets +2 on a Bread Under Siege campaign. An assembly redistributes risk, restores discipline, and turns survival into coordinated strategy.',
    campaignBonus: 2,
    domainBonus: 'EmptyStomach',
  },
];

export default resistanceCards;
