export type IconType =
  | 'bodies'
  | 'evidence'
  | 'defense'
  | 'extraction'
  | 'pool'
  | 'globalGaze'
  | 'warMachine'
  | 'round'
  | 'modeLiberation'
  | 'objective'
  | 'organize'
  | 'investigate'
  | 'launchCampaign'
  | 'buildSolidarity'
  | 'smuggleEvidence'
  | 'internationalOutreach'
  | 'defend'
  | 'playCard'
  | 'advancePhase'
  | 'frontWar'
  | 'frontPlanet'
  | 'frontCage'
  | 'frontTruth'
  | 'frontHunger'
  | 'frontFossil'
  | 'frontVoice'
  | 'ledger'
  | 'seat';

export type IconState = 'default' | 'hover' | 'selected' | 'critical' | 'disabled' | 'gain';
export type IconBaseShape = 'none' | 'circle' | 'hex' | 'diamond' | 'rounded-rect';
