import type { IconBaseShape, IconType } from './iconTypes.ts';

export const ICON_COLORS = {
  bodies: '#8E2C2C',
  evidence: '#2E355F',
  defense: '#5F8D6D',
  extraction: '#1F1F1F',
  pool: '#8B6A3D',
  globalGaze: '#E3A008',
  warMachine: '#A32E2E',
  round: '#D6C7A8',
  modeLiberation: '#C6A75E',
  objective: '#D6C7A8',
  organize: '#8E2C2C',
  investigate: '#2E355F',
  launchCampaign: '#A32E2E',
  buildSolidarity: '#5F8D6D',
  smuggleEvidence: '#8B5E3C',
  internationalOutreach: '#E3A008',
  defend: '#5F8D6D',
  playCard: '#6E4A7E',
  advancePhase: '#8B6A3D',
  frontWar: '#9E1B1B',
  frontPlanet: '#3E6F4F',
  frontCage: '#8B5E3C',
  frontTruth: '#2D3A64',
  frontHunger: '#C9A227',
  frontFossil: '#1F1F1F',
  frontVoice: '#6E4A7E',
  ledger: '#7A4A2E',
  seat: '#C6A75E',
} satisfies Record<IconType, string>;

export const ICON_BASE_SHAPES: Partial<Record<IconType, IconBaseShape>> = {
  bodies: 'circle',
  evidence: 'circle',
  defense: 'circle',
  extraction: 'hex',
  pool: 'circle',
  globalGaze: 'diamond',
  warMachine: 'diamond',
  round: 'diamond',
  modeLiberation: 'rounded-rect',
  objective: 'rounded-rect',
  frontWar: 'rounded-rect',
  frontPlanet: 'rounded-rect',
  frontCage: 'rounded-rect',
  frontTruth: 'rounded-rect',
  frontHunger: 'rounded-rect',
  frontFossil: 'rounded-rect',
  frontVoice: 'rounded-rect',
};
