import type {
  ActionDefinition,
  BeaconDefinition,
  DomainDefinition,
  FactionDefinition,
  RegionDefinition,
  RulesetDefinition,
} from '../../engine/adapters/compat/types.ts';
import { corridorsBurnBoard } from './boards/corridorsBurnBoard.ts';
import { crisisCards } from './decks/crisisDeck.ts';
import { resistanceCards } from './decks/resistanceDeck.ts';
import { systemCards } from './decks/systemEscalationDeck.ts';

const domains: DomainDefinition[] = [
  {
    id: 'WarMachine',
    name: 'War Machine Fracture',
    description: 'Breaking basing chains, arms corridors, and the political tempo of escalation.',
    initialProgress: 1,
  },
  {
    id: 'SilencedTruth',
    name: 'Witness Corridors',
    description: 'Keeping testimony, archives, medics, and public proof in motion under bombardment and blackout.',
    initialProgress: 2,
  },
  {
    id: 'EmptyStomach',
    name: 'Bread Under Siege',
    description: 'Holding food and daily survival against siege, sanctions, and manipulated scarcity.',
    initialProgress: 1,
  },
  {
    id: 'GildedCage',
    name: 'Sanctions Breach',
    description: 'Cracking carceral, financial, and legal siege across borders and banking systems.',
    initialProgress: 1,
  },
  {
    id: 'FossilGrip',
    name: 'Chokepoint Breakage',
    description: 'Interrupting the oil-shipping-basing architecture that treats seas and straits as extractive property.',
    initialProgress: 0,
  },
];

const regions: RegionDefinition[] = [
  {
    id: 'GazaWestBank',
    name: 'Gaza–West Bank',
    description: 'Siege, bombardment, displacement, prison raids, and survival organizing from Gaza to the fragmented West Bank.',
    strapline: 'The moral center bleeds under managed erasure.',
    vulnerability: { WarMachine: 3, GildedCage: 3, SilencedTruth: 2, EmptyStomach: 2 },
  },
  {
    id: 'LebanonNorthernFront',
    name: 'Lebanon–Northern Front',
    description: 'Cross-border escalation, displacement, and the risk that northern war becomes the pretext for wider regional rupture.',
    strapline: 'The frontier expands whenever the war-state needs another horizon.',
    vulnerability: { WarMachine: 3, SilencedTruth: 2, EmptyStomach: 2, GildedCage: 1 },
  },
  {
    id: 'GulfHormuzCorridor',
    name: 'Gulf–Hormuz Corridor',
    description: 'Basing states, insurance markets, oil logistics, and retaliatory fire along the narrowest energy corridor in the theatre.',
    strapline: 'The shipping lane is also a trigger line.',
    vulnerability: { WarMachine: 3, FossilGrip: 3, EmptyStomach: 1, SilencedTruth: 1 },
  },
  {
    id: 'RedSeaSuezCorridor',
    name: 'Red Sea–Suez Corridor',
    description: 'Port labor, Suez choke pressure, Yemeni retaliation, and the long supply chain that keeps war materially alive.',
    strapline: 'Every container route hides a battlefield.',
    vulnerability: { EmptyStomach: 3, FossilGrip: 2, SilencedTruth: 2, WarMachine: 1 },
  },
  {
    id: 'CaribbeanSiege',
    name: 'Caribbean Siege',
    description: 'Pressure on Cuba and Venezuela through sanctions, banking restrictions, oil coercion, platform narratives, and Monroe-style threats.',
    strapline: 'The blockade line moves through ports, banks, and screens.',
    vulnerability: { GildedCage: 3, EmptyStomach: 2, SilencedTruth: 2, FossilGrip: 1 },
  },
  {
    id: 'BlackSeaEasternFurnace',
    name: 'Black Sea–Eastern Furnace',
    description: 'Russia’s continuing war on Ukraine, grain disruption, and the way overextension abroad still feeds the Atlantic war tempo.',
    strapline: 'Another war keeps feeding this one.',
    vulnerability: { WarMachine: 3, EmptyStomach: 2, SilencedTruth: 1, FossilGrip: 1 },
  },
];

const factions: FactionDefinition[] = [
  {
    id: 'palestinian_sumud_committees',
    name: 'Palestinian Sumud Committees',
    shortName: 'Sumud',
    homeRegion: 'GazaWestBank',
    passive: 'Organize gains +2 Comrades in Gaza–West Bank and Launch Campaign gains +1 there.',
    weakness: 'Global Appeal costs +1 Evidence.',
    organizeBonus: 2,
    investigateBonus: 0,
    defenseBonus: 1,
    campaignDomainBonus: 'GildedCage',
    campaignBonus: 1,
    outreachPenalty: 1,
    mandate: {
      id: 'mandate_corridors_sumud',
      title: 'Hold the Ground of Return',
      description: 'End with Gaza–West Bank at 2 or fewer Extraction Tokens, Witness Corridors at 4 or more, and Egyptian Corridor Posture at 3 or more.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'region_extraction', region: 'GazaWestBank' }, op: '<=', right: 2 },
          { kind: 'compare', left: { type: 'domain_progress', domain: 'SilencedTruth' }, op: '>=', right: 4 },
          { kind: 'compare', left: { type: 'custom_track', track: 'egypt_corridor' }, op: '>=', right: 3 },
        ],
      },
    },
    color: '#2f7a4c',
  },
  {
    id: 'gaza_west_bank_witness_medics',
    name: 'Gaza / West Bank Witness and Medics Network',
    shortName: 'Witness',
    homeRegion: 'GazaWestBank',
    passive: 'Investigate gains +1 Evidence in Gaza–West Bank and campaigns on Witness Corridors gain +1.',
    weakness: 'Defend actions gain no home-region bonus.',
    organizeBonus: 0,
    investigateBonus: 1,
    defenseBonus: 0,
    campaignDomainBonus: 'SilencedTruth',
    campaignBonus: 1,
    outreachPenalty: 0,
    mandate: {
      id: 'mandate_corridors_witness',
      title: 'Nothing Must Vanish',
      description: 'End with Witness Corridors at 5 or more, Gaza–West Bank at 2 or fewer Extraction Tokens, and Global Gaze at 10 or more.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'domain_progress', domain: 'SilencedTruth' }, op: '>=', right: 5 },
          { kind: 'compare', left: { type: 'region_extraction', region: 'GazaWestBank' }, op: '<=', right: 2 },
          { kind: 'compare', left: { type: 'global_gaze' }, op: '>=', right: 10 },
        ],
      },
    },
    color: '#2f8088',
  },
  {
    id: 'venezuelan_communal_councils',
    name: 'Venezuelan Communal Councils',
    shortName: 'Communes',
    homeRegion: 'CaribbeanSiege',
    passive: 'Organize gains +2 Comrades in Caribbean Siege and campaigns on Bread Under Siege gain +1 there.',
    weakness: 'Global Appeal costs +1 Evidence.',
    organizeBonus: 2,
    investigateBonus: 0,
    defenseBonus: 1,
    campaignDomainBonus: 'EmptyStomach',
    campaignBonus: 1,
    outreachPenalty: 1,
    mandate: {
      id: 'mandate_corridors_venezuela',
      title: 'Keep the Communes Breathing',
      description: 'End with Caribbean Siege at 2 or fewer Extraction Tokens, Bread Under Siege at 4 or more, and Saudi Posture at least Hedge.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'region_extraction', region: 'CaribbeanSiege' }, op: '<=', right: 2 },
          { kind: 'compare', left: { type: 'domain_progress', domain: 'EmptyStomach' }, op: '>=', right: 4 },
          { kind: 'compare', left: { type: 'custom_track', track: 'saudi_posture' }, op: '>=', right: 1 },
        ],
      },
    },
    color: '#b8862b',
  },
  {
    id: 'cuban_cdr_neighborhood_defense',
    name: 'Cuban CDR and Neighborhood Defense Networks',
    shortName: 'CDRs',
    homeRegion: 'CaribbeanSiege',
    passive: 'Investigate gains +1 Evidence in Caribbean Siege and Defend gains +1 there.',
    weakness: 'Organize outside Caribbean Siege gains no home bonus.',
    organizeBonus: 1,
    investigateBonus: 1,
    defenseBonus: 1,
    campaignDomainBonus: 'SilencedTruth',
    campaignBonus: 1,
    outreachPenalty: 0,
    mandate: {
      id: 'mandate_corridors_cuba',
      title: 'Protect the Blockaded Memory',
      description: 'End with Witness Corridors at 3 or more, Sanctions Breach at 3 or more, and Caribbean Siege at 2 or fewer Extraction Tokens.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'domain_progress', domain: 'SilencedTruth' }, op: '>=', right: 3 },
          { kind: 'compare', left: { type: 'domain_progress', domain: 'GildedCage' }, op: '>=', right: 3 },
          { kind: 'compare', left: { type: 'region_extraction', region: 'CaribbeanSiege' }, op: '<=', right: 2 },
        ],
      },
    },
    color: '#b24738',
  },
  {
    id: 'corridor_workers_refuge_networks',
    name: 'Corridor Workers and Refuge Networks',
    shortName: 'Corridors',
    homeRegion: 'RedSeaSuezCorridor',
    passive: 'Investigate gains +1 Evidence in Red Sea–Suez Corridor and campaigns on Chokepoint Breakage gain +1.',
    weakness: 'Global Appeal costs +1 Evidence when Gulf Blowback is 4 or higher.',
    organizeBonus: 1,
    investigateBonus: 1,
    defenseBonus: 0,
    campaignDomainBonus: 'FossilGrip',
    campaignBonus: 1,
    outreachPenalty: 0,
    mandate: {
      id: 'mandate_corridors_workers',
      title: 'Open the Passage, Not the War',
      description: 'End with Red Sea–Suez Corridor at 2 or fewer Extraction Tokens, Gulf–Hormuz Corridor at 2 or fewer, and Chokepoint Breakage at 4 or more.',
      condition: {
        kind: 'all',
        conditions: [
          { kind: 'compare', left: { type: 'region_extraction', region: 'RedSeaSuezCorridor' }, op: '<=', right: 2 },
          { kind: 'compare', left: { type: 'region_extraction', region: 'GulfHormuzCorridor' }, op: '<=', right: 2 },
          { kind: 'compare', left: { type: 'domain_progress', domain: 'FossilGrip' }, op: '>=', right: 4 },
        ],
      },
    },
    color: '#6b5aa6',
  },
];

const beacons: BeaconDefinition[] = [
  {
    id: 'beacon_corridors_rafah_will_not_be_buried',
    title: 'Rafah Will Not Be Buried',
    description: 'Gaza–West Bank is held at 3 or fewer Extraction Tokens and Global Gaze reaches 8 or more.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'region_extraction', region: 'GazaWestBank' }, op: '<=', right: 3 },
        { kind: 'compare', left: { type: 'global_gaze' }, op: '>=', right: 8 },
      ],
    },
  },
  {
    id: 'beacon_corridors_caribbean_still_breathes',
    title: 'The Caribbean Still Breathes',
    description: 'Caribbean Siege is held at 3 or fewer Extraction Tokens and Sanctions Breach reaches 2 or more.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'region_extraction', region: 'CaribbeanSiege' }, op: '<=', right: 3 },
        { kind: 'compare', left: { type: 'domain_progress', domain: 'GildedCage' }, op: '>=', right: 2 },
      ],
    },
  },
  {
    id: 'beacon_corridors_break_the_shipping_script',
    title: 'Break the Shipping Script',
    description: 'Red Sea–Suez Corridor and Gulf–Hormuz Corridor both drop to 3 or fewer Extraction Tokens and Chokepoint Breakage reaches 2 or more.',
    condition: {
      kind: 'all',
      conditions: [
        { kind: 'compare', left: { type: 'region_extraction', region: 'RedSeaSuezCorridor' }, op: '<=', right: 3 },
        { kind: 'compare', left: { type: 'region_extraction', region: 'GulfHormuzCorridor' }, op: '<=', right: 3 },
        { kind: 'compare', left: { type: 'domain_progress', domain: 'FossilGrip' }, op: '>=', right: 2 },
      ],
    },
  },
];

const actions: ActionDefinition[] = [
  {
    id: 'organize',
    name: 'Organize',
    description: 'Roll 1d6 Comrades into a front, with strong home-region bonuses where movement infrastructure already exists.',
    resolvePriority: 100,
    needsRegion: true,
  },
  {
    id: 'investigate',
    name: 'Investigate',
    description: 'Generate Evidence and draw resistance cards from witness, logistics, and survival networks.',
    resolvePriority: 120,
    needsRegion: true,
  },
  {
    id: 'launch_campaign',
    name: 'Launch Campaign',
    description: 'Commit Comrades and Evidence to a 2d6 campaign against a pressure domain in a chosen front.',
    resolvePriority: 500,
    needsRegion: true,
    needsDomain: true,
    needsComrades: true,
    needsEvidence: true,
    needsCard: true,
    cardType: 'support',
  },
  {
    id: 'build_solidarity',
    name: 'Build Solidarity',
    description: 'Spend 3 Comrades in-region to advance a domain without rolling.',
    resolvePriority: 300,
    needsRegion: true,
    needsDomain: true,
  },
  {
    id: 'smuggle_evidence',
    name: 'Smuggle Evidence',
    description: 'Move Evidence across a pressured corridor to another faction.',
    resolvePriority: 180,
    needsRegion: true,
    needsTargetSeat: true,
  },
  {
    id: 'international_outreach',
    name: 'Global Appeal',
    description: 'Spend Evidence to raise Global Gaze through coordinated testimony and anti-war pressure.',
    resolvePriority: 200,
  },
  {
    id: 'defend',
    name: 'Defend',
    description: 'Convert Comrades into one-round Defense against the next system strike.',
    resolvePriority: 260,
    needsRegion: true,
    needsComrades: true,
  },
  {
    id: 'play_card',
    name: 'Play Card',
    description: 'Resolve an action card from hand for direct tactical impact.',
    resolvePriority: 220,
    needsRegion: true,
    needsCard: true,
    cardType: 'action',
  },
];

export const compatRuleset: RulesetDefinition = {
  id: 'when_the_corridors_burn',
  name: '2026 — WHEN THE CORRIDORS BURN',
  description: 'A corridor war scenario where blockade, shipping, sanctions, basing, and bombardment form one connected system.',
  introduction:
    'March 2026 is not one war. It is a corridor condition stretching from Gaza and south Lebanon through Hormuz and Suez to Havana, Caracas, and the Black Sea. The coalition survives by opening passages the system needs sealed.',
  board: corridorsBurnBoard,
  regions,
  domains,
  factions,
  beacons,
  actions,
  resistanceCards,
  crisisCards,
  systemCards,
  liberationThreshold: 2,
  suddenDeathRound: 13,
  victoryGate: {
    minRoundBeforeVictory: 4,
  },
  victoryScoring: {
    mode: 'score',
    threshold: 65,
    survivalScorePerRound: 0.75,
    components: [
      {
        id: 'publicVictory',
        label: 'Public Victory',
        weight: 30,
        type: 'binaryCondition',
        source: {
          type: 'publicVictory',
        },
      },
    ],
    mandatesAsScore: {
      enabled: true,
      weight: 70,
      mandateProgressMode: 'binary',
    },
    outcomeBands: [
      { id: 'defeat', min: 0, max: 34.999999 },
      { id: 'continuation', min: 35, max: 54.999999 },
      { id: 'win_with_consequence', min: 55, max: 65.999999 },
      { id: 'breakthrough', min: 66, max: 100 },
    ],
  },
  setup: {
    globalGaze: 7,
    northernWarMachine: 8,
    extractionPool: 72,
    extractionSeeds: {
      GazaWestBank: 4,
      LebanonNorthernFront: 1,
      GulfHormuzCorridor: 1,
      RedSeaSuezCorridor: 1,
      CaribbeanSiege: 1,
      BlackSeaEasternFurnace: 0,
    },
    startingComradesByFaction: {
      palestinian_sumud_committees: 10,
      gaza_west_bank_witness_medics: 8,
      venezuelan_communal_councils: 8,
      cuban_cdr_neighborhood_defense: 8,
      corridor_workers_refuge_networks: 8,
    },
    startingEvidenceByFaction: {
      palestinian_sumud_committees: 1,
      gaza_west_bank_witness_medics: 2,
      venezuelan_communal_councils: 1,
      cuban_cdr_neighborhood_defense: 1,
      corridor_workers_refuge_networks: 2,
    },
  },
  customTracks: [
    {
      id: 'egypt_corridor',
      name: 'Egyptian Corridor Posture',
      description: '0-6 track: from sealed containment to pressured opening and mediated passage.',
      initialValue: 2,
      min: 0,
      max: 6,
      thresholds: [2, 4, 5],
    },
    {
      id: 'turkey_corridor',
      name: 'Turkish Corridor Posture',
      description: '0-6 track: from NATO contradiction under management to more visible rupture and corridor pressure.',
      initialValue: 3,
      min: 0,
      max: 6,
      thresholds: [2, 4, 5],
    },
    {
      id: 'jordan_corridor',
      name: 'Jordanian Corridor Posture',
      description: '0-6 track: from containment priority to fragile opening under Palestine-adjacent pressure.',
      initialValue: 2,
      min: 0,
      max: 6,
      thresholds: [2, 4, 5],
    },
    {
      id: 'qatar_corridor',
      name: 'Qatari Mediation Posture',
      description: '0-6 track: mediation capacity under pressure, useful when witness and negotiation both still move.',
      initialValue: 3,
      min: 0,
      max: 6,
      thresholds: [2, 4, 5],
    },
    {
      id: 'gulf_blowback',
      name: 'Gulf Blowback',
      description: 'Shared host-state exposure to retaliatory fire, insurance panic, and basing instability.',
      initialValue: 1,
      min: 0,
      max: 6,
      thresholds: [2, 4, 5],
    },
    {
      id: 'saudi_posture',
      name: 'Saudi Posture',
      description: '0-2 track: 0 host, 1 hedge, 2 distance.',
      initialValue: 1,
      min: 0,
      max: 2,
      thresholds: [1, 2],
    },
    {
      id: 'uae_posture',
      name: 'UAE Posture',
      description: '0-2 track: 0 host, 1 hedge, 2 distance.',
      initialValue: 0,
      min: 0,
      max: 2,
      thresholds: [1, 2],
    },
    {
      id: 'bahrain_posture',
      name: 'Bahrain Posture',
      description: '0-2 track: 0 host, 1 hedge, 2 distance.',
      initialValue: 0,
      min: 0,
      max: 2,
      thresholds: [1, 2],
    },
    {
      id: 'kuwait_posture',
      name: 'Kuwait Posture',
      description: '0-2 track: 0 host, 1 hedge, 2 distance.',
      initialValue: 1,
      min: 0,
      max: 2,
      thresholds: [1, 2],
    },
  ],
  specialRules: [
    {
      id: 'regional_powers_layer',
      label: 'Regional Powers / Corridor States',
      description: 'Egypt, Turkey, Jordan, and Qatar use 0-6 stance tracks. Saudi, UAE, Bahrain, and Kuwait use 0-2 posture tracks under one shared Gulf Blowback meter.',
    },
    {
      id: 'gulf_host_target_subsystem',
      label: 'Host-and-Target Gulf Subsystem',
      description: 'As Gulf Blowback rises, host states fracture or harden. Posture shifts can open space for the coalition without displacing the movements from the center.',
    },
    {
      id: 'atlantic_fracture',
      label: 'Atlantic Fracture',
      description: 'Spain can widen witness and de-escalation openings while the UK can harden Atlantic alignment and war tempo.',
    },
    {
      id: 'corridor_war_not_state_war',
      label: 'Corridor War',
      description: 'Shipping, food, basing, sanctions, and testimony are all fronts. Opening a passage somewhere else can still save Gaza, Cuba, or Venezuela.',
    },
  ],
  scenarioFlags: [
    'spainBreaksRanks',
    'ukAlignmentHardened',
    'rafahGateOpened',
    'qatarChannelActive',
    'gulfTargetsExposed',
  ],
  scenarioHooks: {
    comradesExhaustionGraceRounds: 2,
    thresholdRules: [
      {
        trackId: 'egypt_corridor',
        threshold: 4,
        once: true,
        effects: [
          { type: 'modify_gaze', delta: 1 },
          { type: 'remove_extraction', region: 'GazaWestBank', amount: 1 },
          { type: 'set_scenario_flag', flag: 'rafahGateOpened', value: true },
        ],
      },
      {
        trackId: 'turkey_corridor',
        threshold: 4,
        once: true,
        effects: [
          { type: 'modify_domain', domain: 'WarMachine', delta: 1 },
          { type: 'remove_extraction', region: 'LebanonNorthernFront', amount: 1 },
        ],
      },
      {
        trackId: 'jordan_corridor',
        threshold: 4,
        once: true,
        effects: [
          { type: 'modify_gaze', delta: 1 },
          { type: 'modify_domain', domain: 'GildedCage', delta: 1 },
        ],
      },
      {
        trackId: 'qatar_corridor',
        threshold: 4,
        once: true,
        effects: [
          { type: 'gain_evidence', seat: 0, amount: 1 },
          { type: 'gain_evidence', seat: 1, amount: 1 },
          { type: 'gain_evidence', seat: 2, amount: 1 },
          { type: 'gain_evidence', seat: 3, amount: 1 },
          { type: 'gain_evidence', seat: 4, amount: 1 },
          { type: 'set_scenario_flag', flag: 'qatarChannelActive', value: true },
        ],
      },
      {
        trackId: 'gulf_blowback',
        threshold: 4,
        once: true,
        effects: [
          { type: 'modify_gaze', delta: 1 },
          { type: 'modify_war_machine', delta: 1 },
          { type: 'set_scenario_flag', flag: 'gulfTargetsExposed', value: true },
        ],
      },
      {
        trackId: 'saudi_posture',
        threshold: 2,
        once: true,
        effects: [{ type: 'remove_extraction', region: 'GulfHormuzCorridor', amount: 1 }],
      },
      {
        trackId: 'uae_posture',
        threshold: 2,
        once: true,
        effects: [{ type: 'modify_domain', domain: 'FossilGrip', delta: 1 }],
      },
      {
        trackId: 'bahrain_posture',
        threshold: 2,
        once: true,
        effects: [{ type: 'modify_gaze', delta: 1 }],
      },
      {
        trackId: 'kuwait_posture',
        threshold: 2,
        once: true,
        effects: [{ type: 'modify_domain', domain: 'EmptyStomach', delta: 1 }],
      },
    ],
  },
  victoryConditions: {
    liberation: {
      kind: 'all',
      conditions: [
        { kind: 'every_region_extraction_at_most', count: 4 },
        { kind: 'compare', left: { type: 'global_gaze' }, op: '>=', right: 6 },
        { kind: 'compare', left: { type: 'domain_progress', domain: 'SilencedTruth' }, op: '>=', right: 3 },
      ],
    },
  },
};

export {
  actions,
  beacons,
  crisisCards,
  domains,
  factions,
  regions,
  resistanceCards,
  systemCards,
};

export default compatRuleset;
