import type { ScenarioBoardDefinition } from '../../../engine/index.ts';
import { ALGERIA_SCENARIO_MARKERS, ALGERIA_SCENARIO_TOKEN_ANCHORS } from '../../shared/boards/generatedScenarioAnchors.ts';

export const algeriaBoard: ScenarioBoardDefinition = {
  assetPath: '/assets/scenarios/algerian_war_of_independence/algeria-location-map.svg',
  sourceViewBox: '0 0 1000 800',
  viewport: {
    canvasWidth: '100%',
    canvasHeight: '100%',
    canvasLeft: '0%',
    canvasTop: '0%',
  },
  svgIdConvention: 'GeoJSON-derived Algerian scenario regions with an authored metropole inset.',
  regions: {
    Algiers: {
      regionId: 'Algiers',
      label: 'Algiers',
      marker: { ...ALGERIA_SCENARIO_MARKERS.Algiers },
      tokenAnchor: { ...ALGERIA_SCENARIO_TOKEN_ANCHORS.Algiers },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 68,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '-18px', y: '-24px' },
      tooltipOffset: { x: '-94px', y: '-190px' },
      territoryTilt: '0deg',
      accent: '#8d6746',
      searchTerms: ['algiers', 'capital'],
      focusDomains: ['WarMachine', 'GildedCage', 'SilencedTruth'],
      anchorCoverage: ['algiers-shape'],
      interactionCoverage: ['algiers-shape'],
      svgCoverage: ['algiers-shape'],
      note: 'Urban insurgency front across the capital corridor and colonial seat of power.',
    },
    KabylieMountains: {
      regionId: 'KabylieMountains',
      label: 'Kabylie Mountains',
      marker: { ...ALGERIA_SCENARIO_MARKERS.KabylieMountains },
      tokenAnchor: { ...ALGERIA_SCENARIO_TOKEN_ANCHORS.KabylieMountains },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 72,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '16px', y: '-24px' },
      tooltipOffset: { x: '-82px', y: '-188px' },
      territoryTilt: '-2deg',
      accent: '#a16d4e',
      searchTerms: ['kabylie', 'maquis'],
      focusDomains: ['WarMachine', 'RevolutionaryWave', 'UnfinishedJustice'],
      anchorCoverage: ['kabylie-mountains-shape'],
      interactionCoverage: ['kabylie-mountains-shape'],
      svgCoverage: ['kabylie-mountains-shape'],
      note: 'Kabylia and adjacent mountain fronts where guerrilla endurance and cohesion are forged.',
    },
    Oran: {
      regionId: 'Oran',
      label: 'Oran',
      marker: { ...ALGERIA_SCENARIO_MARKERS.Oran },
      tokenAnchor: { ...ALGERIA_SCENARIO_TOKEN_ANCHORS.Oran },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 68,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '-28px', y: '-22px' },
      tooltipOffset: { x: '-112px', y: '-188px' },
      territoryTilt: '1deg',
      accent: '#9b7d5b',
      searchTerms: ['oran', 'settler'],
      focusDomains: ['EmptyStomach', 'WarMachine', 'GildedCage'],
      anchorCoverage: ['oran-shape'],
      interactionCoverage: ['oran-shape'],
      svgCoverage: ['oran-shape'],
      note: 'Western settler power base and reactionary coastal front.',
    },
    SaharaSouth: {
      regionId: 'SaharaSouth',
      label: 'Sahara South',
      marker: { ...ALGERIA_SCENARIO_MARKERS.SaharaSouth },
      tokenAnchor: { ...ALGERIA_SCENARIO_TOKEN_ANCHORS.SaharaSouth },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 76,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '16px', y: '-12px' },
      tooltipOffset: { x: '-92px', y: '-188px' },
      territoryTilt: '-1deg',
      accent: '#7b5c3d',
      searchTerms: ['sahara', 'south'],
      focusDomains: ['RevolutionaryWave', 'WarMachine', 'EmptyStomach'],
      anchorCoverage: ['sahara-south-shape'],
      interactionCoverage: ['sahara-south-shape'],
      svgCoverage: ['sahara-south-shape'],
      note: 'Saharan organizing front where distance and reprisal test endurance.',
    },
    TunisianBorder: {
      regionId: 'TunisianBorder',
      label: 'Tunisian Border',
      marker: { ...ALGERIA_SCENARIO_MARKERS.TunisianBorder },
      tokenAnchor: { ...ALGERIA_SCENARIO_TOKEN_ANCHORS.TunisianBorder },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 68,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '18px', y: '-20px' },
      tooltipOffset: { x: '-88px', y: '-188px' },
      territoryTilt: '2deg',
      accent: '#c18d5b',
      searchTerms: ['tunisia', 'border'],
      focusDomains: ['SilencedTruth', 'WarMachine', 'UnfinishedJustice'],
      anchorCoverage: ['tunisian-border-shape'],
      interactionCoverage: ['tunisian-border-shape'],
      svgCoverage: ['tunisian-border-shape'],
      note: 'Eastern frontier for supply, witness, and movement across the Tunisian corridor.',
    },
    FrenchMetropoleInfluence: {
      regionId: 'FrenchMetropoleInfluence',
      label: 'French Metropole Influence',
      marker: { ...ALGERIA_SCENARIO_MARKERS.FrenchMetropoleInfluence },
      tokenAnchor: { ...ALGERIA_SCENARIO_TOKEN_ANCHORS.FrenchMetropoleInfluence },
      anchorBias: { x: 0, y: 0 },
      clusterRadius: 62,
      labelOffsetY: -14,
      opticalCenteringByTokenType: { extraction: { x: 0, y: -1 }, defense: { x: 0, y: 0 }, comrades: { x: 0, y: 0.5 } },
      labelOffset: { x: '-44px', y: '-30px' },
      tooltipOffset: { x: '-126px', y: '-192px' },
      territoryTilt: '0deg',
      accent: '#6d4c41',
      searchTerms: ['metropole', 'france'],
      focusDomains: ['EmptyStomach', 'SilencedTruth', 'UnfinishedJustice'],
      anchorCoverage: ['french-metropole-influence-shape'],
      interactionCoverage: ['french-metropole-influence-shape'],
      svgCoverage: ['french-metropole-influence-shape'],
      note: 'Inset front representing political and media struggle inside metropolitan France.',
    },
  },
};
